/********************************************************************
* LendaBarDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LendaBarDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLendaBarDictionary();
extern void G__cpp_setup_inheritanceLendaBarDictionary();
extern void G__cpp_setup_typetableLendaBarDictionary();
extern void G__cpp_setup_memvarLendaBarDictionary();
extern void G__cpp_setup_globalLendaBarDictionary();
extern void G__cpp_setup_memfuncLendaBarDictionary();
extern void G__cpp_setup_funcLendaBarDictionary();
extern void G__set_cpp_environmentLendaBarDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LendaBar.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LendaBarDictionaryLN_TClass;
extern G__linked_taginfo G__LendaBarDictionaryLN_TBuffer;
extern G__linked_taginfo G__LendaBarDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__LendaBarDictionaryLN_TObject;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_string;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_LendaChannel;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_LendaBar;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiterator;
extern G__linked_taginfo G__LendaBarDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlELendaChannelmUcOallocatorlELendaChannelmUgRsPgR;
extern G__linked_taginfo G__LendaBarDictionaryLN_vectorlELendaChannelmUcOallocatorlELendaChannelmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LendaBarDictionaryLN_reverse_iteratorlEvectorlELendaChannelmUcOallocatorlELendaChannelmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<LendaChannel,allocator<LendaChannel> > G__vectorlELendaChannelcOallocatorlELendaChannelgRsPgR;
typedef vector<LendaChannel*,allocator<LendaChannel*> > G__vectorlELendaChannelmUcOallocatorlELendaChannelmUgRsPgR;
