/********************************************************************
* LendaChannelDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LendaChannelDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLendaChannelDictionary();
extern void G__cpp_setup_inheritanceLendaChannelDictionary();
extern void G__cpp_setup_typetableLendaChannelDictionary();
extern void G__cpp_setup_memvarLendaChannelDictionary();
extern void G__cpp_setup_globalLendaChannelDictionary();
extern void G__cpp_setup_memfuncLendaChannelDictionary();
extern void G__cpp_setup_funcLendaChannelDictionary();
extern void G__set_cpp_environmentLendaChannelDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LendaChannel.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LendaChannelDictionaryLN_TClass;
extern G__linked_taginfo G__LendaChannelDictionaryLN_TBuffer;
extern G__linked_taginfo G__LendaChannelDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__LendaChannelDictionaryLN_TObject;
extern G__linked_taginfo G__LendaChannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_string;
extern G__linked_taginfo G__LendaChannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_LendaChannel;
extern G__linked_taginfo G__LendaChannelDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LendaChannelDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
