/********************************************************************
* LendaPackerDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LendaPackerDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLendaPackerDictionary();
extern void G__cpp_setup_inheritanceLendaPackerDictionary();
extern void G__cpp_setup_typetableLendaPackerDictionary();
extern void G__cpp_setup_memvarLendaPackerDictionary();
extern void G__cpp_setup_globalLendaPackerDictionary();
extern void G__cpp_setup_memfuncLendaPackerDictionary();
extern void G__cpp_setup_funcLendaPackerDictionary();
extern void G__set_cpp_environmentLendaPackerDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LendaPacker.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_string;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_LendaFilter;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_LendaChannel;
extern G__linked_taginfo G__LendaPackerDictionaryLN_LendaBar;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_LendaEvent;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaBarcOallocatorlELendaBargRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_ddaschannel;
extern G__linked_taginfo G__LendaPackerDictionaryLN_DDASEvent;
extern G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_R00TLeSettings;
extern G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_MapInfo;
extern G__linked_taginfo G__LendaPackerDictionaryLN_LendaPacker;
extern G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOLendaBarcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOLendaBargRsPgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_multimaplEintcORefTimeContainercOlesslEintgRcOallocatorlEpairlEconstsPintcORefTimeContainergRsPgRsPgR;
extern G__linked_taginfo G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR;

/* STUB derived class for protected member access */
