//
// File generated by rootcint at Mon Oct  2 14:09:01 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME LendaPackerDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LendaPackerDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::MapInfo MapInfo;
      #else
      class MapInfo  {
         public:
         //friend XX;
         double EnergySlope; ///<Slope for energy calibration of light output.
         double EnergyIntercept; ///<Intercept for energy calibration of light output
         double TOFOffset; ///<Constant time offset (in clock tics) used in Corrected Times
         string FullName; ///<Full Channel Name. Exmaple: SL01T
         string BarName; ///<Name of Bar. Example: SL01
         string ReferenceName; ///<Full Reference channel Name. Example: OBJ1T
         double BarAngle; ///<The angle of bar relative to the beam direction
         bool HasCorrections; ///<Flag to be set when there is correction information available
         bool IsAReferenceChannel; //
         int ReferenceGlobalID; //
         int GlobalID; //
         int FL; ///<Timing filter Rise length
         int FG; ///<Timing filter Gap Length
         int d; ///<Timing filter CFD delay
         int w; ///<Timing filter CFD scale factor
         bool DontTraceAnalyze; //
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::LendaPacker LendaPacker;
      #else
      class LendaPacker  {
         public:
         //friend XX;
         ::LendaFilter theFilter; ///<Instance of the LendaFilter class which preforms the wave form analysis
         vector< Double_t > thisEventsFF; ///<Temporary place for each channels fast filter.  Gets reset when Reset is called
         vector< Double_t > thisEventsCFD; ///<Temporary place for each channels digital CFD.  Gets reset when Reset is called
         map< int, ::string > GlobalIDToFullLocal; //
         map< ::string, int > FullLocalToGlobalID; //
         map< int, ::string > GlobalIDToBar; //
         map< ::string, int > BarNameToUniqueBarNumber; //
         map< ::string, Double_t > BarNameToBarAngle; //
         map< int, ::MapInfo > GlobalIDToMapInfo; //
         string _mapFileName; //
         string _correctionsFileName; //
         bool saveTraces; //
         double lg; //
         double sg; //
         double lg2; //
         double sg2; //
         int traceDelay; //
         G__int64 jentry; //
         int thisChannelsNumZeroCrossings; //
         vector< Double_t > thisChannelsEnergies; //
         vector< Int_t > thisChannelsPulseHeights; //
         vector< Double_t > thisChannelsSoftwareCFDs; //
         vector< Double_t > thisChannelsCubicCFDs; //
         vector< Double_t > thisChannelsLE; //
         vector< Int_t > thisChannelsPeakSpots; //
         vector< Double_t > thisChannelsUnderShoots; //
         int thisEventsFilterHeight; //
         double longGate; //
         double shortGate; //
         double filter_energy; //Member variable for trapezoidal digital energy filter (JPC 4/3/2018)
         double cubicFitCFD; //
         double start; //
         double thisChannelsCFDResidual; //
         string referenceChannelPattern; //A string to define what channel names will be considered the reference channels ex OBJ
         ::R00TLeSettings* theSettings; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MapInfo_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void MapInfo_Dictionary();
   static void *new_MapInfo(void *p = 0);
   static void *newArray_MapInfo(Long_t size, void *p);
   static void delete_MapInfo(void *p);
   static void deleteArray_MapInfo(void *p);
   static void destruct_MapInfo(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MapInfo*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::MapInfo) == sizeof( ::ROOTShadow::Shadow::MapInfo));
      ::MapInfo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::MapInfo),0);
      static ::ROOT::TGenericClassInfo 
         instance("MapInfo", "./LendaPacker.hh", 58,
                  typeid(::MapInfo), ::ROOT::DefineBehavior(ptr, ptr),
                  &MapInfo_ShowMembers, &MapInfo_Dictionary, isa_proxy, 4,
                  sizeof(::MapInfo) );
      instance.SetNew(&new_MapInfo);
      instance.SetNewArray(&newArray_MapInfo);
      instance.SetDelete(&delete_MapInfo);
      instance.SetDeleteArray(&deleteArray_MapInfo);
      instance.SetDestructor(&destruct_MapInfo);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MapInfo*)
   {
      return GenerateInitInstanceLocal((::MapInfo*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MapInfo*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void MapInfo_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::MapInfo*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void LendaPacker_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void LendaPacker_Dictionary();
   static void *new_LendaPacker(void *p = 0);
   static void *newArray_LendaPacker(Long_t size, void *p);
   static void delete_LendaPacker(void *p);
   static void deleteArray_LendaPacker(void *p);
   static void destruct_LendaPacker(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::LendaPacker*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::LendaPacker) == sizeof( ::ROOTShadow::Shadow::LendaPacker));
      ::LendaPacker *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::LendaPacker),0);
      static ::ROOT::TGenericClassInfo 
         instance("LendaPacker", "./LendaPacker.hh", 176,
                  typeid(::LendaPacker), ::ROOT::DefineBehavior(ptr, ptr),
                  &LendaPacker_ShowMembers, &LendaPacker_Dictionary, isa_proxy, 4,
                  sizeof(::LendaPacker) );
      instance.SetNew(&new_LendaPacker);
      instance.SetNewArray(&newArray_LendaPacker);
      instance.SetDelete(&delete_LendaPacker);
      instance.SetDeleteArray(&deleteArray_LendaPacker);
      instance.SetDestructor(&destruct_LendaPacker);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::LendaPacker*)
   {
      return GenerateInitInstanceLocal((::LendaPacker*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::LendaPacker*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void LendaPacker_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::LendaPacker*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void MapInfo_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class MapInfo.
      typedef ::ROOTShadow::Shadow::MapInfo ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::MapInfo*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EnergySlope", &sobj->EnergySlope);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EnergyIntercept", &sobj->EnergyIntercept);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TOFOffset", &sobj->TOFOffset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FullName", (void*)&sobj->FullName);
      R__insp.InspectMember("string", (void*)&sobj->FullName, "FullName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BarName", (void*)&sobj->BarName);
      R__insp.InspectMember("string", (void*)&sobj->BarName, "BarName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ReferenceName", (void*)&sobj->ReferenceName);
      R__insp.InspectMember("string", (void*)&sobj->ReferenceName, "ReferenceName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BarAngle", &sobj->BarAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "HasCorrections", &sobj->HasCorrections);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IsAReferenceChannel", &sobj->IsAReferenceChannel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ReferenceGlobalID", &sobj->ReferenceGlobalID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GlobalID", &sobj->GlobalID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FL", &sobj->FL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FG", &sobj->FG);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d", &sobj->d);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "w", &sobj->w);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DontTraceAnalyze", &sobj->DontTraceAnalyze);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_MapInfo(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MapInfo : new ::MapInfo;
   }
   static void *newArray_MapInfo(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MapInfo[nElements] : new ::MapInfo[nElements];
   }
   // Wrapper around operator delete
   static void delete_MapInfo(void *p) {
      delete ((::MapInfo*)p);
   }
   static void deleteArray_MapInfo(void *p) {
      delete [] ((::MapInfo*)p);
   }
   static void destruct_MapInfo(void *p) {
      typedef ::MapInfo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::MapInfo

//______________________________________________________________________________
namespace ROOTDict {
   void LendaPacker_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class LendaPacker.
      typedef ::ROOTShadow::Shadow::LendaPacker ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::LendaPacker*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theFilter", &sobj->theFilter);
      R__insp.InspectMember(sobj->theFilter, "theFilter.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisEventsFF", (void*)&sobj->thisEventsFF);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisEventsFF, "thisEventsFF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisEventsCFD", (void*)&sobj->thisEventsCFD);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisEventsCFD, "thisEventsCFD.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GlobalIDToFullLocal", (void*)&sobj->GlobalIDToFullLocal);
      R__insp.InspectMember("map<int,string>", (void*)&sobj->GlobalIDToFullLocal, "GlobalIDToFullLocal.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FullLocalToGlobalID", (void*)&sobj->FullLocalToGlobalID);
      R__insp.InspectMember("map<string,int>", (void*)&sobj->FullLocalToGlobalID, "FullLocalToGlobalID.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GlobalIDToBar", (void*)&sobj->GlobalIDToBar);
      R__insp.InspectMember("map<int,string>", (void*)&sobj->GlobalIDToBar, "GlobalIDToBar.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BarNameToUniqueBarNumber", (void*)&sobj->BarNameToUniqueBarNumber);
      R__insp.InspectMember("map<string,int>", (void*)&sobj->BarNameToUniqueBarNumber, "BarNameToUniqueBarNumber.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BarNameToBarAngle", (void*)&sobj->BarNameToBarAngle);
      R__insp.InspectMember("map<string,Double_t>", (void*)&sobj->BarNameToBarAngle, "BarNameToBarAngle.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GlobalIDToMapInfo", (void*)&sobj->GlobalIDToMapInfo);
      R__insp.InspectMember("map<int,MapInfo>", (void*)&sobj->GlobalIDToMapInfo, "GlobalIDToMapInfo.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_mapFileName", (void*)&sobj->_mapFileName);
      R__insp.InspectMember("string", (void*)&sobj->_mapFileName, "_mapFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_correctionsFileName", (void*)&sobj->_correctionsFileName);
      R__insp.InspectMember("string", (void*)&sobj->_correctionsFileName, "_correctionsFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "saveTraces", &sobj->saveTraces);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lg", &sobj->lg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sg", &sobj->sg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lg2", &sobj->lg2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sg2", &sobj->sg2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "traceDelay", &sobj->traceDelay);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "jentry", &sobj->jentry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsNumZeroCrossings", &sobj->thisChannelsNumZeroCrossings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsEnergies", (void*)&sobj->thisChannelsEnergies);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisChannelsEnergies, "thisChannelsEnergies.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsPulseHeights", (void*)&sobj->thisChannelsPulseHeights);
      R__insp.InspectMember("vector<Int_t>", (void*)&sobj->thisChannelsPulseHeights, "thisChannelsPulseHeights.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsSoftwareCFDs", (void*)&sobj->thisChannelsSoftwareCFDs);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisChannelsSoftwareCFDs, "thisChannelsSoftwareCFDs.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsCubicCFDs", (void*)&sobj->thisChannelsCubicCFDs);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisChannelsCubicCFDs, "thisChannelsCubicCFDs.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsLE", (void*)&sobj->thisChannelsLE);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisChannelsLE, "thisChannelsLE.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsPeakSpots", (void*)&sobj->thisChannelsPeakSpots);
      R__insp.InspectMember("vector<Int_t>", (void*)&sobj->thisChannelsPeakSpots, "thisChannelsPeakSpots.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsUnderShoots", (void*)&sobj->thisChannelsUnderShoots);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->thisChannelsUnderShoots, "thisChannelsUnderShoots.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisEventsFilterHeight", &sobj->thisEventsFilterHeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "longGate", &sobj->longGate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shortGate", &sobj->shortGate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "filter_energy", &sobj->filter_energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cubicFitCFD", &sobj->cubicFitCFD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "start", &sobj->start);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thisChannelsCFDResidual", &sobj->thisChannelsCFDResidual);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "referenceChannelPattern", (void*)&sobj->referenceChannelPattern);
      R__insp.InspectMember("string", (void*)&sobj->referenceChannelPattern, "referenceChannelPattern.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*theSettings", &sobj->theSettings);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_LendaPacker(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::LendaPacker : new ::LendaPacker;
   }
   static void *newArray_LendaPacker(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::LendaPacker[nElements] : new ::LendaPacker[nElements];
   }
   // Wrapper around operator delete
   static void delete_LendaPacker(void *p) {
      delete ((::LendaPacker*)p);
   }
   static void deleteArray_LendaPacker(void *p) {
      delete [] ((::LendaPacker*)p);
   }
   static void destruct_LendaPacker(void *p) {
      typedef ::LendaPacker current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::LendaPacker

namespace ROOTDict {
   void maplEintcOMapInfogR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEintcOMapInfogR_Dictionary();
   static void *new_maplEintcOMapInfogR(void *p = 0);
   static void *newArray_maplEintcOMapInfogR(Long_t size, void *p);
   static void delete_maplEintcOMapInfogR(void *p);
   static void deleteArray_maplEintcOMapInfogR(void *p);
   static void destruct_maplEintcOMapInfogR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<int,MapInfo>*)
   {
      map<int,MapInfo> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<int,MapInfo>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<int,MapInfo>", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/map", 63,
                  typeid(map<int,MapInfo>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEintcOMapInfogR_Dictionary, isa_proxy, 0,
                  sizeof(map<int,MapInfo>) );
      instance.SetNew(&new_maplEintcOMapInfogR);
      instance.SetNewArray(&newArray_maplEintcOMapInfogR);
      instance.SetDelete(&delete_maplEintcOMapInfogR);
      instance.SetDeleteArray(&deleteArray_maplEintcOMapInfogR);
      instance.SetDestructor(&destruct_maplEintcOMapInfogR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<int,MapInfo> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<int,MapInfo>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEintcOMapInfogR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<int,MapInfo>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEintcOMapInfogR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,MapInfo> : new map<int,MapInfo>;
   }
   static void *newArray_maplEintcOMapInfogR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,MapInfo>[nElements] : new map<int,MapInfo>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEintcOMapInfogR(void *p) {
      delete ((map<int,MapInfo>*)p);
   }
   static void deleteArray_maplEintcOMapInfogR(void *p) {
      delete [] ((map<int,MapInfo>*)p);
   }
   static void destruct_maplEintcOMapInfogR(void *p) {
      typedef map<int,MapInfo> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<int,MapInfo>

namespace ROOTDict {
   void maplEintcOstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEintcOstringgR_Dictionary();
   static void *new_maplEintcOstringgR(void *p = 0);
   static void *newArray_maplEintcOstringgR(Long_t size, void *p);
   static void delete_maplEintcOstringgR(void *p);
   static void deleteArray_maplEintcOstringgR(void *p);
   static void destruct_maplEintcOstringgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<int,string>*)
   {
      map<int,string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<int,string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<int,string>", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/map", 63,
                  typeid(map<int,string>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEintcOstringgR_Dictionary, isa_proxy, 0,
                  sizeof(map<int,string>) );
      instance.SetNew(&new_maplEintcOstringgR);
      instance.SetNewArray(&newArray_maplEintcOstringgR);
      instance.SetDelete(&delete_maplEintcOstringgR);
      instance.SetDeleteArray(&deleteArray_maplEintcOstringgR);
      instance.SetDestructor(&destruct_maplEintcOstringgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<int,string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<int,string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEintcOstringgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<int,string>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEintcOstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,string> : new map<int,string>;
   }
   static void *newArray_maplEintcOstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,string>[nElements] : new map<int,string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEintcOstringgR(void *p) {
      delete ((map<int,string>*)p);
   }
   static void deleteArray_maplEintcOstringgR(void *p) {
      delete [] ((map<int,string>*)p);
   }
   static void destruct_maplEintcOstringgR(void *p) {
      typedef map<int,string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<int,string>

namespace ROOTDict {
   void maplEstringcOdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOdoublegR_Dictionary();
   static void *new_maplEstringcOdoublegR(void *p = 0);
   static void *newArray_maplEstringcOdoublegR(Long_t size, void *p);
   static void delete_maplEstringcOdoublegR(void *p);
   static void deleteArray_maplEstringcOdoublegR(void *p);
   static void destruct_maplEstringcOdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<string,double>*)
   {
      map<string,double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,double>", -2, "map.dll", 0,
                  typeid(map<string,double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,double>) );
      instance.SetNew(&new_maplEstringcOdoublegR);
      instance.SetNewArray(&newArray_maplEstringcOdoublegR);
      instance.SetDelete(&delete_maplEstringcOdoublegR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
      instance.SetDestructor(&destruct_maplEstringcOdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<string,double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEstringcOdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
   }
   static void *newArray_maplEstringcOdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOdoublegR(void *p) {
      delete ((map<string,double>*)p);
   }
   static void deleteArray_maplEstringcOdoublegR(void *p) {
      delete [] ((map<string,double>*)p);
   }
   static void destruct_maplEstringcOdoublegR(void *p) {
      typedef map<string,double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<string,double>

namespace ROOTDict {
   void maplEstringcOintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOintgR_Dictionary();
   static void *new_maplEstringcOintgR(void *p = 0);
   static void *newArray_maplEstringcOintgR(Long_t size, void *p);
   static void delete_maplEstringcOintgR(void *p);
   static void deleteArray_maplEstringcOintgR(void *p);
   static void destruct_maplEstringcOintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<string,int>*)
   {
      map<string,int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,int>", -2, "map.dll", 0,
                  typeid(map<string,int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,int>) );
      instance.SetNew(&new_maplEstringcOintgR);
      instance.SetNewArray(&newArray_maplEstringcOintgR);
      instance.SetDelete(&delete_maplEstringcOintgR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
      instance.SetDestructor(&destruct_maplEstringcOintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<string,int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEstringcOintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
   }
   static void *newArray_maplEstringcOintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOintgR(void *p) {
      delete ((map<string,int>*)p);
   }
   static void deleteArray_maplEstringcOintgR(void *p) {
      delete [] ((map<string,int>*)p);
   }
   static void destruct_maplEstringcOintgR(void *p) {
      typedef map<string,int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<string,int>

namespace ROOTDict {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<double>

namespace ROOTDict {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<int>

/********************************************************
* LendaPackerDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableLendaPackerDictionary();

extern "C" void G__set_cpp_environmentLendaPackerDictionary() {
  G__cpp_reset_tagtableLendaPackerDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevLendaPackerDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MapInfo */
static int G__LendaPackerDictionary_496_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MapInfo* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MapInfo[n];
     } else {
       p = new((void*) gvp) MapInfo[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MapInfo;
     } else {
       p = new((void*) gvp) MapInfo;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_496_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MapInfo*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LendaPackerDictionary_496_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MapInfo* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MapInfo(*(MapInfo*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MapInfo G__TMapInfo;
static int G__LendaPackerDictionary_496_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MapInfo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MapInfo*) (soff+(sizeof(MapInfo)*i)))->~G__TMapInfo();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MapInfo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MapInfo*) (soff))->~G__TMapInfo();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LendaPackerDictionary_496_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MapInfo* dest = (MapInfo*) G__getstructoffset();
   *dest = *(MapInfo*) libp->para[0].ref;
   const MapInfo& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* LendaPacker */
static int G__LendaPackerDictionary_498_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LendaPacker* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new LendaPacker[n];
     } else {
       p = new((void*) gvp) LendaPacker[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new LendaPacker;
     } else {
       p = new((void*) gvp) LendaPacker;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LendaPacker* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new LendaPacker((R00TLeSettings*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) LendaPacker((R00TLeSettings*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->SetSettingFileNames(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->CalcTimeFilters(*(vector<UShort_t>*) libp->para[0].ref, *((MapInfo*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->CalcEnergyGates(*(vector<UShort_t>*) libp->para[0].ref, *((MapInfo*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->CalcAll(*(vector<UShort_t>*) libp->para[0].ref, *((MapInfo*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->CalcAll((ddaschannel*) G__int(libp->para[0]), *((MapInfo*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->CalcAll((LendaChannel*) G__int(libp->para[0]), *((MapInfo*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->ForceAllBarFilters((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->ForceAllReferenceFilters((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->ForceAllFilters((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->SetGates((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->SetTraceDelay((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->SetJEntry((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->MakeLendaEvent((LendaEvent*) G__int(libp->para[0]), (DDASEvent*) G__int(libp->para[1])
, (Long64_t) G__Longlong(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->ReMakeLendaEvent((LendaEvent*) G__int(libp->para[0]), (LendaEvent*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((LendaPacker*) G__getstructoffset())->RePackChannel((LendaChannel*) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((LendaPacker*) G__getstructoffset())->RePackChannel((LendaChannel*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         LendaChannel* pobj;
         LendaChannel xobj = ((LendaPacker*) G__getstructoffset())->DDASChannel2LendaChannel((ddaschannel*) G__int(libp->para[0]), *((MapInfo*) G__int(libp->para[1])));
         pobj = new LendaChannel(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->RePackSoftwareTimes((LendaEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->PackEvent((LendaEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->RePackEvent((LendaEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaPacker*) G__getstructoffset())->FindAndSetMapAndCorrectionsFileNames((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaPackerDictionary_498_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         MapInfo* pobj;
         MapInfo xobj = ((LendaPacker*) G__getstructoffset())->GetMapInfo(*((string*) G__int(libp->para[0])));
         pobj = new MapInfo(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LendaPackerDictionary_498_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   LendaPacker* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new LendaPacker(*(LendaPacker*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef LendaPacker G__TLendaPacker;
static int G__LendaPackerDictionary_498_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (LendaPacker*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((LendaPacker*) (soff+(sizeof(LendaPacker)*i)))->~G__TLendaPacker();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (LendaPacker*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((LendaPacker*) (soff))->~G__TLendaPacker();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LendaPackerDictionary_498_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LendaPacker* dest = (LendaPacker*) G__getstructoffset();
   *dest = *(LendaPacker*) libp->para[0].ref;
   const LendaPacker& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MapInfo */

/* LendaPacker */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncLendaPackerDictionary {
 public:
  G__Sizep2memfuncLendaPackerDictionary(): p(&G__Sizep2memfuncLendaPackerDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncLendaPackerDictionary::*p)();
};

size_t G__get_sizep2memfuncLendaPackerDictionary()
{
  G__Sizep2memfuncLendaPackerDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceLendaPackerDictionary() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableLendaPackerDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<LendaChannel>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<LendaBar>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaBarcOallocatorlELendaBargRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaBarcOallocatorlELendaBargRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ddaschannel*>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string,less<int> >",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,LendaBar>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOLendaBarcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOLendaBargRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,LendaBar,less<string> >",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOLendaBarcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOLendaBargRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<int,RefTimeContainer>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_multimaplEintcORefTimeContainercOlesslEintgRcOallocatorlEpairlEconstsPintcORefTimeContainergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<int,RefTimeContainer,less<int> >",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_multimaplEintcORefTimeContainercOlesslEintgRcOallocatorlEpairlEconstsPintcORefTimeContainergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,Double_t>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,MapInfo>",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,MapInfo,less<int> >",117,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MapInfo */
static void G__setup_memvarMapInfo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo));
   { MapInfo *p; p=(MapInfo*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->EnergySlope)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"EnergySlope=",0,"/<Slope for energy calibration of light output.");
   G__memvar_setup((void*)((long)(&p->EnergyIntercept)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"EnergyIntercept=",0,"/<Intercept for energy calibration of light output");
   G__memvar_setup((void*)((long)(&p->TOFOffset)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TOFOffset=",0,"/<Constant time offset (in clock tics) used in Corrected Times");
   G__memvar_setup((void*)((long)(&p->FullName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_string),-1,-1,1,"FullName=",0,"/<Full Channel Name. Exmaple: SL01T");
   G__memvar_setup((void*)((long)(&p->BarName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_string),-1,-1,1,"BarName=",0,"/<Name of Bar. Example: SL01");
   G__memvar_setup((void*)((long)(&p->ReferenceName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_string),-1,-1,1,"ReferenceName=",0,"/<Full Reference channel Name. Example: OBJ1T");
   G__memvar_setup((void*)((long)(&p->BarAngle)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"BarAngle=",0,"/<The angle of bar relative to the beam direction");
   G__memvar_setup((void*)((long)(&p->HasCorrections)-(long)(p)),103,0,0,-1,-1,-1,1,"HasCorrections=",0,"/<Flag to be set when there is correction information available");
   G__memvar_setup((void*)((long)(&p->IsAReferenceChannel)-(long)(p)),103,0,0,-1,-1,-1,1,"IsAReferenceChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ReferenceGlobalID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ReferenceGlobalID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GlobalID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"GlobalID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FL)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"FL=",0,"/<Timing filter Rise length");
   G__memvar_setup((void*)((long)(&p->FG)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"FG=",0,"/<Timing filter Gap Length");
   G__memvar_setup((void*)((long)(&p->d)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"d=",0,"/<Timing filter CFD delay");
   G__memvar_setup((void*)((long)(&p->w)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"w=",0,"/<Timing filter CFD scale factor");
   G__memvar_setup((void*)((long)(&p->DontTraceAnalyze)-(long)(p)),103,0,0,-1,-1,-1,1,"DontTraceAnalyze=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* LendaPacker */
static void G__setup_memvarLendaPacker(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker));
   { LendaPacker *p; p=(LendaPacker*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->theFilter)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaFilter),-1,-1,1,"theFilter=",0,"/<Instance of the LendaFilter class which preforms the wave form analysis");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisEventsFF=",0,"/<Temporary place for each channels fast filter.  Gets reset when Reset is called");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisEventsCFD=",0,"/<Temporary place for each channels digital CFD.  Gets reset when Reset is called");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),G__defined_typename("map<int,string>"),-1,4,"GlobalIDToFullLocal=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<string,int>"),-1,4,"FullLocalToGlobalID=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),G__defined_typename("map<int,string>"),-1,4,"GlobalIDToBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<string,int>"),-1,4,"BarNameToUniqueBarNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<string,Double_t>"),-1,4,"BarNameToBarAngle=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR),G__defined_typename("map<int,MapInfo>"),-1,4,"GlobalIDToMapInfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_string),-1,-1,4,"_mapFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_string),-1,-1,4,"_correctionsFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"saveTraces=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"lg=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"sg=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"lg2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"sg2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"traceDelay=",0,(char*)NULL);
   G__memvar_setup((void*)0,110,0,0,-1,G__defined_typename("Long64_t"),-1,4,"jentry=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"thisChannelsNumZeroCrossings=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisChannelsEnergies=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,4,"thisChannelsPulseHeights=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisChannelsSoftwareCFDs=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisChannelsCubicCFDs=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisChannelsLE=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,4,"thisChannelsPeakSpots=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"thisChannelsUnderShoots=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"thisEventsFilterHeight=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"longGate=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"shortGate=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"filter_energy=",0,"Member variable for trapezoidal digital energy filter (JPC 4/3/2018)");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"cubicFitCFD=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"start=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"thisChannelsCFDResidual=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_string),-1,-1,4,"referenceChannelPattern=",0,"A string to define what channel names will be considered the reference channels ex OBJ");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LendaPackerDictionaryLN_R00TLeSettings),-1,-1,4,"theSettings=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarLendaPackerDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMapInfo(void) {
   /* MapInfo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo));
   G__memfunc_setup("MapInfo",682,G__LendaPackerDictionary_496_0_1, 105, G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__LendaPackerDictionary_496_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("MapInfo", 682, G__LendaPackerDictionary_496_0_3, (int) ('i'), G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo), -1, 0, 1, 1, 1, 0, "u 'MapInfo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MapInfo", 808, G__LendaPackerDictionary_496_0_4, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LendaPackerDictionary_496_0_5, (int) ('u'), G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo), -1, 1, 1, 1, 1, 0, "u 'MapInfo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncLendaPacker(void) {
   /* LendaPacker */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker));
   G__memfunc_setup("LendaPacker",1082,G__LendaPackerDictionary_498_0_1, 105, G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker), -1, 0, 0, 1, 1, 0, "", "/<Defualt constructor ", (void*) NULL, 0);
   G__memfunc_setup("LendaPacker",1082,G__LendaPackerDictionary_498_0_2, 105, G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker), -1, 0, 1, 1, 1, 0, "U 'R00TLeSettings' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSettingFileNames",1918,G__LendaPackerDictionary_498_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - MapFileName u 'string' - 0 - CorrectionsFileName", "/<Set the filenames for Corrections/Map file.  Looks in prm directory.  Calls BuildMaps", (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__LendaPackerDictionary_498_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcTimeFilters",1499,G__LendaPackerDictionary_498_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - theTrace u 'MapInfo' - 0 - info", "/<Call waveform timing analysis routines provided by the LendaFilter object", (void*) NULL, 0);
   G__memfunc_setup("CalcEnergyGates",1489,G__LendaPackerDictionary_498_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - theTrace u 'MapInfo' - 0 - info", "/<Call the waveform energy analysis routines provided by the LendaFilter object", (void*) NULL, 0);
   G__memfunc_setup("CalcAll",652,G__LendaPackerDictionary_498_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - theTrace u 'MapInfo' - 0 - info", "/<Call all waveform analysis routines", (void*) NULL, 0);
   G__memfunc_setup("CalcAll",652,G__LendaPackerDictionary_498_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'ddaschannel' - 0 - c u 'MapInfo' - 0 - info", "/<Call all waveform analysis routines", (void*) NULL, 0);
   G__memfunc_setup("CalcAll",652,G__LendaPackerDictionary_498_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'LendaChannel' - 0 - c u 'MapInfo' - 0 - info", "/<Call all waveform analysis routines", (void*) NULL, 0);
   G__memfunc_setup("ForceAllBarFilters",1782,G__LendaPackerDictionary_498_0_10, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - FL i - 'Int_t' 0 - FG "
"i - 'Int_t' 0 - d i - 'Int_t' 0 - w", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ForceAllReferenceFilters",2416,G__LendaPackerDictionary_498_0_11, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - FL i - 'Int_t' 0 - FG "
"i - 'Int_t' 0 - d i - 'Int_t' 0 - w", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ForceAllFilters",1505,G__LendaPackerDictionary_498_0_12, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - FL i - 'Int_t' 0 - FG "
"i - 'Int_t' 0 - d i - 'Int_t' 0 - w", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGates",800,G__LendaPackerDictionary_498_0_13, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - - d - 'Double_t' 0 - - "
"d - 'Double_t' 0 - - d - 'Double_t' 0 - -", "/<Set parameters for the waveform energy analysis routines", (void*) NULL, 0);
   G__memfunc_setup("SetTraceDelay",1290,G__LendaPackerDictionary_498_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - x", "/<Set the trace delay value", (void*) NULL, 0);
   G__memfunc_setup("SetJEntry",904,G__LendaPackerDictionary_498_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - n", "/<Set the entry number that this event had in the RAW tree", (void*) NULL, 0);
   G__memfunc_setup("MakeLendaEvent",1380,G__LendaPackerDictionary_498_0_16, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'LendaEvent' - 0 - Event U 'DDASEvent' - 0 - theDDASEvent "
"n - 'Long64_t' 0 - jentry", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReMakeLendaEvent",1563,G__LendaPackerDictionary_498_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'LendaEvent' - 0 - inEvent U 'LendaEvent' - 0 - outEvent", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RePackChannel",1263,G__LendaPackerDictionary_498_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'LendaChannel' - 0 - - g - - 0 'false' isAnObject", "/<RePack a LendaChannel.  Used in ReMakeLendaEvent", (void*) NULL, 0);
   G__memfunc_setup("DDASChannel2LendaChannel",2212,G__LendaPackerDictionary_498_0_19, 117, G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaChannel), -1, 0, 2, 1, 1, 0, 
"U 'ddaschannel' - 0 - c u 'MapInfo' - 0 - info", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RePackSoftwareTimes",1923,G__LendaPackerDictionary_498_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "U 'LendaEvent' - 0 - Event", "/<OBSOLETE!!!!!", (void*) NULL, 0);
   G__memfunc_setup("PackEvent",897,G__LendaPackerDictionary_498_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "U 'LendaEvent' - 0 - Event", "/<OBSOLETE!!!", (void*) NULL, 0);
   G__memfunc_setup("RePackEvent",1080,G__LendaPackerDictionary_498_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "U 'LendaEvent' - 0 - Event", "/<OBSOLETE!!!", (void*) NULL, 0);
   G__memfunc_setup("FindAndSetMapAndCorrectionsFileNames",3568,G__LendaPackerDictionary_498_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - RunNumber", "/<Looks in prm directory for map/corrections files and sets them", (void*) NULL, 0);
   G__memfunc_setup("GetMapInfo",970,G__LendaPackerDictionary_498_0_24, 117, G__get_linked_tagnum(&G__LendaPackerDictionaryLN_MapInfo), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - FullName", "/<Get the MapInfo for a channel ", (void*) NULL, 0);
   G__memfunc_setup("BuildMaps",897,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "/<Method to build Maps for all the corrections and map file information", (void*) NULL, 0);
   G__memfunc_setup("PutDDASChannelInBar",1754,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"u 'MapInfo' - 0 - info u 'LendaBar' - 1 - theBar "
"U 'ddaschannel' - 0 - theChannel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PackCalculatedValues",2017,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"U 'LendaChannel' - 0 - - u 'MapInfo' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillReferenceTimesInEvent",2513,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'LendaEvent' - 0 - Event u 'map<string,LendaBar,less<string>,allocator<pair<const string,LendaBar> > >' 'map<string,LendaBar>' 1 - ThisEventsBars "
"u 'multimap<int,RefTimeContainer,less<int>,allocator<pair<const int,RefTimeContainer> > >' 'multimap<int,RefTimeContainer>' 1 - GlobalIDToReferenceTimes", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateSettings",1460,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("LendaPacker", 1082, G__LendaPackerDictionary_498_0_30, (int) ('i'), G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker), -1, 0, 1, 1, 1, 0, "u 'LendaPacker' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~LendaPacker", 1208, G__LendaPackerDictionary_498_0_31, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LendaPackerDictionary_498_0_32, (int) ('u'), G__get_linked_tagnum(&G__LendaPackerDictionaryLN_LendaPacker), -1, 1, 1, 1, 1, 0, "u 'LendaPacker' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncLendaPackerDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalLendaPackerDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcLendaPackerDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_LendaFilter = { "LendaFilter" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_LendaChannel = { "LendaChannel" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_LendaBar = { "LendaBar" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR = { "vector<LendaChannel,allocator<LendaChannel> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<LendaChannel,allocator<LendaChannel> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_LendaEvent = { "LendaEvent" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR = { "vector<LendaBar,allocator<LendaBar> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaBarcOallocatorlELendaBargRsPgRcLcLiteratorgR = { "reverse_iterator<vector<LendaBar,allocator<LendaBar> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_ddaschannel = { "ddaschannel" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_DDASEvent = { "DDASEvent" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR = { "vector<ddaschannel*,allocator<ddaschannel*> >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ddaschannel*,allocator<ddaschannel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_R00TLeSettings = { "R00TLeSettings" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR = { "map<int,string,less<int>,allocator<pair<const int,string> > >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_MapInfo = { "MapInfo" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_LendaPacker = { "LendaPacker" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_maplEstringcOLendaBarcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOLendaBargRsPgRsPgR = { "map<string,LendaBar,less<string>,allocator<pair<const string,LendaBar> > >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_multimaplEintcORefTimeContainercOlesslEintgRcOallocatorlEpairlEconstsPintcORefTimeContainergRsPgRsPgR = { "multimap<int,RefTimeContainer,less<int>,allocator<pair<const int,RefTimeContainer> > >" , 99 , -1 };
G__linked_taginfo G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR = { "map<int,MapInfo,less<int>,allocator<pair<const int,MapInfo> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableLendaPackerDictionary() {
  G__LendaPackerDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_string.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_LendaFilter.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_LendaChannel.tagnum = -1 ;
  G__LendaPackerDictionaryLN_LendaBar.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_LendaEvent.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaBarcOallocatorlELendaBargRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_ddaschannel.tagnum = -1 ;
  G__LendaPackerDictionaryLN_DDASEvent.tagnum = -1 ;
  G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_R00TLeSettings.tagnum = -1 ;
  G__LendaPackerDictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_MapInfo.tagnum = -1 ;
  G__LendaPackerDictionaryLN_LendaPacker.tagnum = -1 ;
  G__LendaPackerDictionaryLN_maplEstringcOLendaBarcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOLendaBargRsPgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_multimaplEintcORefTimeContainercOlesslEintgRcOallocatorlEpairlEconstsPintcORefTimeContainergRsPgRsPgR.tagnum = -1 ;
  G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableLendaPackerDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_string);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_LendaFilter);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_LendaChannel);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_LendaBar);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlELendaChannelcOallocatorlELendaChannelgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaChannelcOallocatorlELendaChannelgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_LendaEvent);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlELendaBarcOallocatorlELendaBargRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlELendaBarcOallocatorlELendaBargRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_ddaschannel);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_DDASEvent);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_R00TLeSettings);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_MapInfo),sizeof(MapInfo),-1,262400,(char*)NULL,G__setup_memvarMapInfo,G__setup_memfuncMapInfo);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_LendaPacker),sizeof(LendaPacker),-1,296192,(char*)NULL,G__setup_memvarLendaPacker,G__setup_memfuncLendaPacker);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_maplEstringcOLendaBarcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOLendaBargRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_multimaplEintcORefTimeContainercOlesslEintgRcOallocatorlEpairlEconstsPintcORefTimeContainergRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaPackerDictionaryLN_maplEintcOMapInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOMapInfogRsPgRsPgR);
}
extern "C" void G__cpp_setupLendaPackerDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupLendaPackerDictionary()");
  G__set_cpp_environmentLendaPackerDictionary();
  G__cpp_setup_tagtableLendaPackerDictionary();

  G__cpp_setup_inheritanceLendaPackerDictionary();

  G__cpp_setup_typetableLendaPackerDictionary();

  G__cpp_setup_memvarLendaPackerDictionary();

  G__cpp_setup_memfuncLendaPackerDictionary();
  G__cpp_setup_globalLendaPackerDictionary();
  G__cpp_setup_funcLendaPackerDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncLendaPackerDictionary();
  return;
}
class G__cpp_setup_initLendaPackerDictionary {
  public:
    G__cpp_setup_initLendaPackerDictionary() { G__add_setup_func("LendaPackerDictionary",(G__incsetup)(&G__cpp_setupLendaPackerDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initLendaPackerDictionary() { G__remove_setup_func("LendaPackerDictionary"); }
};
G__cpp_setup_initLendaPackerDictionary G__cpp_setup_initializerLendaPackerDictionary;

