//
// File generated by rootcint at Mon Oct  2 14:08:45 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ddaschannelDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ddaschannelDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void ddaschannel_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ddaschannel(void *p = 0);
   static void *newArray_ddaschannel(Long_t size, void *p);
   static void delete_ddaschannel(void *p);
   static void deleteArray_ddaschannel(void *p);
   static void destruct_ddaschannel(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ddaschannel*)
   {
      ::ddaschannel *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ddaschannel >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ddaschannel", ::ddaschannel::Class_Version(), "./ddaschannel.hh", 43,
                  typeid(::ddaschannel), ::ROOT::DefineBehavior(ptr, ptr),
                  &::ddaschannel::Dictionary, isa_proxy, 4,
                  sizeof(::ddaschannel) );
      instance.SetNew(&new_ddaschannel);
      instance.SetNewArray(&newArray_ddaschannel);
      instance.SetDelete(&delete_ddaschannel);
      instance.SetDeleteArray(&deleteArray_ddaschannel);
      instance.SetDestructor(&destruct_ddaschannel);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ddaschannel*)
   {
      return GenerateInitInstanceLocal((::ddaschannel*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ddaschannel*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr ddaschannel::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *ddaschannel::Class_Name()
{
   return "ddaschannel";
}

//______________________________________________________________________________
const char *ddaschannel::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::ddaschannel*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ddaschannel::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::ddaschannel*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ddaschannel::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::ddaschannel*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ddaschannel::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::ddaschannel*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void ddaschannel::Streamer(TBuffer &R__b)
{
   // Stream an object of class ddaschannel.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ddaschannel::Class(),this);
   } else {
      R__b.WriteClassBuffer(ddaschannel::Class(),this);
   }
}

//______________________________________________________________________________
void ddaschannel::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ddaschannel.
      TClass *R__cl = ::ddaschannel::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "time", &time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cfd", &cfd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energy", &energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timehigh", &timehigh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timelow", &timelow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timecfd", &timecfd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "channelnum", &channelnum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "finishcode", &finishcode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "channellength", &channellength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "channelheaderlength", &channelheaderlength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "overflowcode", &overflowcode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chanid", &chanid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "slotid", &slotid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "crateid", &crateid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "id", &id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cfdtrigsourcebit", &cfdtrigsourcebit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tracelength", &tracelength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energySums", (void*)&energySums);
      R__insp.InspectMember("vector<UInt_t>", (void*)&energySums, "energySums.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "qdcSums", (void*)&qdcSums);
      R__insp.InspectMember("vector<UShort_t>", (void*)&qdcSums, "qdcSums.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "exclocklow", &exclocklow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "exclockhigh", &exclockhigh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "exclock", &exclock);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "has_esum", &has_esum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "has_qdc", &has_qdc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "has_exclock", &has_exclock);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trace", (void*)&trace);
      R__insp.InspectMember("vector<UShort_t>", (void*)&trace, "trace.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_ddaschannel(void *p) {
      return  p ? new(p) ::ddaschannel : new ::ddaschannel;
   }
   static void *newArray_ddaschannel(Long_t nElements, void *p) {
      return p ? new(p) ::ddaschannel[nElements] : new ::ddaschannel[nElements];
   }
   // Wrapper around operator delete
   static void delete_ddaschannel(void *p) {
      delete ((::ddaschannel*)p);
   }
   static void deleteArray_ddaschannel(void *p) {
      delete [] ((::ddaschannel*)p);
   }
   static void destruct_ddaschannel(void *p) {
      typedef ::ddaschannel current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::ddaschannel

namespace ROOTDict {
   void vectorlEunsignedsPintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPintgR_Dictionary();
   static void *new_vectorlEunsignedsPintgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPintgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPintgR(void *p);
   static void deleteArray_vectorlEunsignedsPintgR(void *p);
   static void destruct_vectorlEunsignedsPintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned int>*)
   {
      vector<unsigned int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned int>", -2, "vector.dll", 0,
                  typeid(vector<unsigned int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned int>) );
      instance.SetNew(&new_vectorlEunsignedsPintgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPintgR);
      instance.SetDelete(&delete_vectorlEunsignedsPintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPintgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<unsigned int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<unsigned int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned int> : new vector<unsigned int>;
   }
   static void *newArray_vectorlEunsignedsPintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned int>[nElements] : new vector<unsigned int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPintgR(void *p) {
      delete ((vector<unsigned int>*)p);
   }
   static void deleteArray_vectorlEunsignedsPintgR(void *p) {
      delete [] ((vector<unsigned int>*)p);
   }
   static void destruct_vectorlEunsignedsPintgR(void *p) {
      typedef vector<unsigned int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<unsigned int>

namespace ROOTDict {
   void vectorlEunsignedsPshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPshortgR_Dictionary();
   static void *new_vectorlEunsignedsPshortgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPshortgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPshortgR(void *p);
   static void deleteArray_vectorlEunsignedsPshortgR(void *p);
   static void destruct_vectorlEunsignedsPshortgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned short>*)
   {
      vector<unsigned short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned short>", -2, "vector.dll", 0,
                  typeid(vector<unsigned short>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned short>) );
      instance.SetNew(&new_vectorlEunsignedsPshortgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPshortgR);
      instance.SetDelete(&delete_vectorlEunsignedsPshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPshortgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPshortgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<unsigned short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPshortgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<unsigned short>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short> : new vector<unsigned short>;
   }
   static void *newArray_vectorlEunsignedsPshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short>[nElements] : new vector<unsigned short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPshortgR(void *p) {
      delete ((vector<unsigned short>*)p);
   }
   static void deleteArray_vectorlEunsignedsPshortgR(void *p) {
      delete [] ((vector<unsigned short>*)p);
   }
   static void destruct_vectorlEunsignedsPshortgR(void *p) {
      typedef vector<unsigned short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<unsigned short>

/********************************************************
* ddaschannelDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableddaschannelDictionary();

extern "C" void G__set_cpp_environmentddaschannelDictionary() {
  G__cpp_reset_tagtableddaschannelDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevddaschannelDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ddaschannel */
static int G__ddaschannelDictionary_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ddaschannel* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ddaschannel[n];
     } else {
       p = new((void*) gvp) ddaschannel[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ddaschannel;
     } else {
       p = new((void*) gvp) ddaschannel;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ddaschannel* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new ddaschannel(*(ddaschannel*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) ddaschannel(*(ddaschannel*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ddaschannel& obj = ((ddaschannel*) G__getstructoffset())->operator=(*(ddaschannel*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((ddaschannel*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((ddaschannel*) G__getstructoffset())->GetTimeHigh());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((ddaschannel*) G__getstructoffset())->GetTimeLow());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((ddaschannel*) G__getstructoffset())->GetCFDTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ddaschannel*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ddaschannel*) G__getstructoffset())->GetCFD());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((ddaschannel*) G__getstructoffset())->GetEnergySums((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetChannelNum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetFinishCode());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetChannelLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetChannelLengthHeader());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetOverflowCode());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetSlotID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetCrateID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetChannelID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((ddaschannel*) G__getstructoffset())->GetID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((ddaschannel*) G__getstructoffset())->GetCFDTriggerSourceBit());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<UShort_t>* pobj;
         vector<UShort_t> xobj = ((ddaschannel*) G__getstructoffset())->GetTrace();
         pobj = new vector<UShort_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetChannelID((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetSlotID((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetCrateID((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetChannelHeaderLength((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetChannelLength((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetOverflowCode((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetFinishCode((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetID((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetCFDTriggerSourceBit((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetTimeLow((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetTimeHigh((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetTimeCFD((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetTime();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetEnergy((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetTraceLength((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetExClockLow((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetExClockHigh((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetExClock();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetEnergySums((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetQDCSums((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->SetTraceValues((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->UnpackChannelData((const uint32_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ddaschannel::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ddaschannel::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ddaschannel::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ddaschannel::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ddaschannel*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ddaschannel::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ddaschannel::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ddaschannel::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ddaschannelDictionary_168_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ddaschannel::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ddaschannel G__Tddaschannel;
static int G__ddaschannelDictionary_168_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ddaschannel*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ddaschannel*) (soff+(sizeof(ddaschannel)*i)))->~G__Tddaschannel();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ddaschannel*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ddaschannel*) (soff))->~G__Tddaschannel();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ddaschannel */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncddaschannelDictionary {
 public:
  G__Sizep2memfuncddaschannelDictionary(): p(&G__Sizep2memfuncddaschannelDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncddaschannelDictionary::*p)();
};

size_t G__get_sizep2memfuncddaschannelDictionary()
{
  G__Sizep2memfuncddaschannelDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceddaschannelDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel))) {
     ddaschannel *G__Lderived;
     G__Lderived=(ddaschannel*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel),G__get_linked_tagnum(&G__ddaschannelDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableddaschannelDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint32_t",104,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ddaschannel */
static void G__setup_memvarddaschannel(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel));
   { ddaschannel *p; p=(ddaschannel*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"time=",0,"/< Assembled time including cfd from module");
   G__memvar_setup((void*)((long)(&p->cfd)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"cfd=",0,"/< Cfd time only from module");
   G__memvar_setup((void*)((long)(&p->energy)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"energy=",0,"/< Energy of event from energy filter");
   G__memvar_setup((void*)((long)(&p->timehigh)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"timehigh=",0,"/< portion of timestamp");
   G__memvar_setup((void*)((long)(&p->timelow)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"timelow=",0,"/< portion of timestamp");
   G__memvar_setup((void*)((long)(&p->timecfd)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"timecfd=",0,"/< portion of timestamp");
   G__memvar_setup((void*)((long)(&p->channelnum)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"channelnum=",0,"/< obsolete");
   G__memvar_setup((void*)((long)(&p->finishcode)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"finishcode=",0,"/< indicate whether event is ");
   G__memvar_setup((void*)((long)(&p->channellength)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"channellength=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->channelheaderlength)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"channelheaderlength=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->overflowcode)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"overflowcode=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chanid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"chanid=",0,"/<Channel in module");
   G__memvar_setup((void*)((long)(&p->slotid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"slotid=",0,"/<Slot in crate");
   G__memvar_setup((void*)((long)(&p->crateid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"crateid=",0,"/<Crate ID");
   G__memvar_setup((void*)((long)(&p->id)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"id=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cfdtrigsourcebit)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"cfdtrigsourcebit=",0,"/< cfd trigger source bit, 0- even, 1 - odd");
   G__memvar_setup((void*)((long)(&p->tracelength)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"tracelength=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->energySums)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<UInt_t>"),-1,1,"energySums=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->qdcSums)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"qdcSums=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->exclocklow)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"exclocklow=",0,"/< portion of of external clock: bits 0-15");
   G__memvar_setup((void*)((long)(&p->exclockhigh)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"exclockhigh=",0,"/< portion of of external clock: bits 16-31            ");
   G__memvar_setup((void*)((long)(&p->exclock)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"exclock=",0,"/< external clock");
   G__memvar_setup((void*)((long)(&p->has_esum)-(long)(p)),103,0,0,-1,-1,-1,1,"has_esum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->has_qdc)-(long)(p)),103,0,0,-1,-1,-1,1,"has_qdc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->has_exclock)-(long)(p)),103,0,0,-1,-1,-1,1,"has_exclock=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trace)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"trace=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ddaschannelDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarddaschannelDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncddaschannel(void) {
   /* ddaschannel */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel));
   G__memfunc_setup("ddaschannel",1141,G__ddaschannelDictionary_168_0_1, 105, G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ddaschannel",1141,G__ddaschannelDictionary_168_0_2, 105, G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel), -1, 0, 1, 1, 1, 0, "u 'ddaschannel' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__ddaschannelDictionary_168_0_3, 117, G__get_linked_tagnum(&G__ddaschannelDictionaryLN_ddaschannel), -1, 1, 1, 1, 1, 0, "u 'ddaschannel' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__ddaschannelDictionary_168_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__ddaschannelDictionary_168_0_5, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimeHigh",1071,G__ddaschannelDictionary_168_0_6, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimeLow",993,G__ddaschannelDictionary_168_0_7, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCFDTime",892,G__ddaschannelDictionary_168_0_8, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__ddaschannelDictionary_168_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCFD",493,G__ddaschannelDictionary_168_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergySums",1330,G__ddaschannelDictionary_168_0_11, 104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChannelNum",1289,G__ddaschannelDictionary_168_0_12, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFinishCode",1276,G__ddaschannelDictionary_168_0_13, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChannelLength",1595,G__ddaschannelDictionary_168_0_14, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChannelLengthHeader",2180,G__ddaschannelDictionary_168_0_15, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOverflowCode",1519,G__ddaschannelDictionary_168_0_16, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSlotID",847,G__ddaschannelDictionary_168_0_17, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCrateID",924,G__ddaschannelDictionary_168_0_18, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChannelID",1126,G__ddaschannelDictionary_168_0_19, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetID",429,G__ddaschannelDictionary_168_0_20, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCFDTriggerSourceBit",2129,G__ddaschannelDictionary_168_0_21, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrace",783,G__ddaschannelDictionary_168_0_22, 117, G__get_linked_tagnum(&G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR), G__defined_typename("vector<UShort_t>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChannelID",1138,G__ddaschannelDictionary_168_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSlotID",859,G__ddaschannelDictionary_168_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCrateID",936,G__ddaschannelDictionary_168_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChannelHeaderLength",2192,G__ddaschannelDictionary_168_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChannelLength",1607,G__ddaschannelDictionary_168_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOverflowCode",1531,G__ddaschannelDictionary_168_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFinishCode",1288,G__ddaschannelDictionary_168_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetID",441,G__ddaschannelDictionary_168_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCFDTriggerSourceBit",2141,G__ddaschannelDictionary_168_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimeLow",1005,G__ddaschannelDictionary_168_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimeHigh",1083,G__ddaschannelDictionary_168_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimeCFD",904,G__ddaschannelDictionary_168_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTime",699,G__ddaschannelDictionary_168_0_35, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__ddaschannelDictionary_168_0_36, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTraceLength",1405,G__ddaschannelDictionary_168_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetExClockLow",1287,G__ddaschannelDictionary_168_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetExClockHigh",1365,G__ddaschannelDictionary_168_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetExClock",981,G__ddaschannelDictionary_168_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergySums",1342,G__ddaschannelDictionary_168_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetQDCSums",940,G__ddaschannelDictionary_168_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTraceValues",1419,G__ddaschannelDictionary_168_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnpackChannelData",1685,G__ddaschannelDictionary_168_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "H - 'uint32_t' 10 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ddaschannelDictionary_168_0_45, 85, G__get_linked_tagnum(&G__ddaschannelDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ddaschannel::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ddaschannelDictionary_168_0_46, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ddaschannel::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ddaschannelDictionary_168_0_47, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ddaschannel::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ddaschannelDictionary_168_0_48, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ddaschannel::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ddaschannelDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ddaschannelDictionary_168_0_52, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ddaschannelDictionary_168_0_53, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ddaschannel::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ddaschannelDictionary_168_0_54, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ddaschannel::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ddaschannelDictionary_168_0_55, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ddaschannel::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ddaschannelDictionary_168_0_56, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ddaschannel::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~ddaschannel", 1267, G__ddaschannelDictionary_168_0_57, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncddaschannelDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalddaschannelDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcddaschannelDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ddaschannelDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ddaschannelDictionaryLN_ddaschannel = { "ddaschannel" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableddaschannelDictionary() {
  G__ddaschannelDictionaryLN_TClass.tagnum = -1 ;
  G__ddaschannelDictionaryLN_TBuffer.tagnum = -1 ;
  G__ddaschannelDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__ddaschannelDictionaryLN_TObject.tagnum = -1 ;
  G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__ddaschannelDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__ddaschannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ddaschannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ddaschannelDictionaryLN_ddaschannel.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableddaschannelDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ddaschannelDictionaryLN_ddaschannel),sizeof(ddaschannel),-1,294656,(char*)NULL,G__setup_memvarddaschannel,G__setup_memfuncddaschannel);
}
extern "C" void G__cpp_setupddaschannelDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupddaschannelDictionary()");
  G__set_cpp_environmentddaschannelDictionary();
  G__cpp_setup_tagtableddaschannelDictionary();

  G__cpp_setup_inheritanceddaschannelDictionary();

  G__cpp_setup_typetableddaschannelDictionary();

  G__cpp_setup_memvarddaschannelDictionary();

  G__cpp_setup_memfuncddaschannelDictionary();
  G__cpp_setup_globalddaschannelDictionary();
  G__cpp_setup_funcddaschannelDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncddaschannelDictionary();
  return;
}
class G__cpp_setup_initddaschannelDictionary {
  public:
    G__cpp_setup_initddaschannelDictionary() { G__add_setup_func("ddaschannelDictionary",(G__incsetup)(&G__cpp_setupddaschannelDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initddaschannelDictionary() { G__remove_setup_func("ddaschannelDictionary"); }
};
G__cpp_setup_initddaschannelDictionary G__cpp_setup_initializerddaschannelDictionary;

