//
// File generated by rootcint at Mon Oct  2 14:08:45 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DDASEventDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DDASEventDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void DDASEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DDASEvent(void *p = 0);
   static void *newArray_DDASEvent(Long_t size, void *p);
   static void delete_DDASEvent(void *p);
   static void deleteArray_DDASEvent(void *p);
   static void destruct_DDASEvent(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::DDASEvent*)
   {
      ::DDASEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DDASEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DDASEvent", ::DDASEvent::Class_Version(), "./DDASEvent.hh", 21,
                  typeid(::DDASEvent), ::ROOT::DefineBehavior(ptr, ptr),
                  &::DDASEvent::Dictionary, isa_proxy, 4,
                  sizeof(::DDASEvent) );
      instance.SetNew(&new_DDASEvent);
      instance.SetNewArray(&newArray_DDASEvent);
      instance.SetDelete(&delete_DDASEvent);
      instance.SetDeleteArray(&deleteArray_DDASEvent);
      instance.SetDestructor(&destruct_DDASEvent);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::DDASEvent*)
   {
      return GenerateInitInstanceLocal((::DDASEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DDASEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr DDASEvent::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *DDASEvent::Class_Name()
{
   return "DDASEvent";
}

//______________________________________________________________________________
const char *DDASEvent::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::DDASEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DDASEvent::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::DDASEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DDASEvent::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::DDASEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DDASEvent::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::DDASEvent*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void DDASEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class DDASEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DDASEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(DDASEvent::Class(),this);
   }
}

//______________________________________________________________________________
void DDASEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DDASEvent.
      TClass *R__cl = ::DDASEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_data", (void*)&m_data);
      R__insp.InspectMember("vector<ddaschannel*>", (void*)&m_data, "m_data.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_DDASEvent(void *p) {
      return  p ? new(p) ::DDASEvent : new ::DDASEvent;
   }
   static void *newArray_DDASEvent(Long_t nElements, void *p) {
      return p ? new(p) ::DDASEvent[nElements] : new ::DDASEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_DDASEvent(void *p) {
      delete ((::DDASEvent*)p);
   }
   static void deleteArray_DDASEvent(void *p) {
      delete [] ((::DDASEvent*)p);
   }
   static void destruct_DDASEvent(void *p) {
      typedef ::DDASEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::DDASEvent

namespace ROOTDict {
   void vectorlEddaschannelmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEddaschannelmUgR_Dictionary();
   static void *new_vectorlEddaschannelmUgR(void *p = 0);
   static void *newArray_vectorlEddaschannelmUgR(Long_t size, void *p);
   static void delete_vectorlEddaschannelmUgR(void *p);
   static void deleteArray_vectorlEddaschannelmUgR(void *p);
   static void destruct_vectorlEddaschannelmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<ddaschannel*>*)
   {
      vector<ddaschannel*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<ddaschannel*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<ddaschannel*>", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<ddaschannel*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEddaschannelmUgR_Dictionary, isa_proxy, 4,
                  sizeof(vector<ddaschannel*>) );
      instance.SetNew(&new_vectorlEddaschannelmUgR);
      instance.SetNewArray(&newArray_vectorlEddaschannelmUgR);
      instance.SetDelete(&delete_vectorlEddaschannelmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEddaschannelmUgR);
      instance.SetDestructor(&destruct_vectorlEddaschannelmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<ddaschannel*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<ddaschannel*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEddaschannelmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<ddaschannel*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEddaschannelmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<ddaschannel*> : new vector<ddaschannel*>;
   }
   static void *newArray_vectorlEddaschannelmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<ddaschannel*>[nElements] : new vector<ddaschannel*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEddaschannelmUgR(void *p) {
      delete ((vector<ddaschannel*>*)p);
   }
   static void deleteArray_vectorlEddaschannelmUgR(void *p) {
      delete [] ((vector<ddaschannel*>*)p);
   }
   static void destruct_vectorlEddaschannelmUgR(void *p) {
      typedef vector<ddaschannel*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<ddaschannel*>

/********************************************************
* DDASEventDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDDASEventDictionary();

extern "C" void G__set_cpp_environmentDDASEventDictionary() {
  G__cpp_reset_tagtableDDASEventDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevDDASEventDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DDASEvent */
static int G__DDASEventDictionary_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DDASEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DDASEvent[n];
     } else {
       p = new((void*) gvp) DDASEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DDASEvent;
     } else {
       p = new((void*) gvp) DDASEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DDASEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DDASEvent(*(DDASEvent*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) DDASEvent(*(DDASEvent*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const DDASEvent& obj = ((DDASEvent*) G__getstructoffset())->operator=(*(DDASEvent*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ddaschannel*>& obj = ((DDASEvent*) G__getstructoffset())->GetData();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DDASEvent*) G__getstructoffset())->AddChannelData((ddaschannel*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const DDASEvent*) G__getstructoffset())->GetNEvents());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const DDASEvent*) G__getstructoffset())->GetFirstTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const DDASEvent*) G__getstructoffset())->GetLastTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const DDASEvent*) G__getstructoffset())->GetTimeWidth());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DDASEvent*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DDASEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DDASEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DDASEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DDASEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DDASEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DDASEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DDASEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DDASEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DDASEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DDASEvent G__TDDASEvent;
static int G__DDASEventDictionary_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DDASEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DDASEvent*) (soff+(sizeof(DDASEvent)*i)))->~G__TDDASEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DDASEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DDASEvent*) (soff))->~G__TDDASEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* vector<ddaschannel*,allocator<ddaschannel*> > */
static int G__DDASEventDictionary_171_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::reference obj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->at((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         G__letint(result7, 'U', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::const_reference obj = ((const vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->at((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         G__letint(result7, 'U', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::iterator* pobj;
         vector<ddaschannel*,allocator<ddaschannel*> >::iterator xobj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->begin();
         pobj = new vector<ddaschannel*,allocator<ddaschannel*> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::iterator* pobj;
         vector<ddaschannel*,allocator<ddaschannel*> >::iterator xobj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->end();
         pobj = new vector<ddaschannel*,allocator<ddaschannel*> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator* pobj;
         vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator xobj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->rbegin();
         pobj = new vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator* pobj;
         vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator xobj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->rend();
         pobj = new vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->max_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->resize((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->resize((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]), (ddaschannel*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->capacity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->empty());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::reference obj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->operator[]((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         G__letint(result7, 'U', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::const_reference obj = ((const vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->operator[]((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         G__letint(result7, 'U', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ddaschannel*,allocator<ddaschannel*> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ddaschannel*,allocator<ddaschannel*> >[n];
     } else {
       p = new((void*) gvp) vector<ddaschannel*,allocator<ddaschannel*> >[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ddaschannel*,allocator<ddaschannel*> >;
     } else {
       p = new((void*) gvp) vector<ddaschannel*,allocator<ddaschannel*> >;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ddaschannel*,allocator<ddaschannel*> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ddaschannel*,allocator<ddaschannel*> >((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(ddaschannel**) libp->para[1].ref : *(ddaschannel**) (void*) (&G__Mlong(libp->para[1])));
     } else {
       p = new((void*) gvp) vector<ddaschannel*,allocator<ddaschannel*> >((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(ddaschannel**) libp->para[1].ref : *(ddaschannel**) (void*) (&G__Mlong(libp->para[1])));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<ddaschannel*,allocator<ddaschannel*> >((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) vector<ddaschannel*,allocator<ddaschannel*> >((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ddaschannel*,allocator<ddaschannel*> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<ddaschannel*,allocator<ddaschannel*> >(*(vector<ddaschannel*,allocator<ddaschannel*> >*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) vector<ddaschannel*,allocator<ddaschannel*> >(*(vector<ddaschannel*,allocator<ddaschannel*> >*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<ddaschannel*,allocator<ddaschannel*> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<ddaschannel*,allocator<ddaschannel*> >(*((vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator*) G__int(libp->para[0])), *((vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator*) G__int(libp->para[1])));
   } else {
     p = new((void*) gvp) vector<ddaschannel*,allocator<ddaschannel*> >(*((vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator*) G__int(libp->para[0])), *((vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator*) G__int(libp->para[1])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ddaschannel*,allocator<ddaschannel*> >& obj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->operator=(*(vector<ddaschannel*,allocator<ddaschannel*> >*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->reserve((vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         ddaschannel*& obj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->front();
         result7->ref = (long) (&obj);
         G__letint(result7, 'U', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         ddaschannel*& obj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->back();
         result7->ref = (long) (&obj);
         G__letint(result7, 'U', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->push_back(libp->para[0].ref ? *(ddaschannel**) libp->para[0].ref : *(ddaschannel**) (void*) (&G__Mlong(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->swap(*(vector<ddaschannel*,allocator<ddaschannel*> >*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<ddaschannel*,allocator<ddaschannel*> >::iterator* pobj;
         vector<ddaschannel*,allocator<ddaschannel*> >::iterator xobj = ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->insert(*((vector<ddaschannel*,allocator<ddaschannel*> >::iterator*) G__int(libp->para[0])), libp->para[1].ref ? *(ddaschannel**) libp->para[1].ref : *(ddaschannel**) (void*) (&G__Mlong(libp->para[1])));
         pobj = new vector<ddaschannel*,allocator<ddaschannel*> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->insert(*((vector<ddaschannel*,allocator<ddaschannel*> >::iterator*) G__int(libp->para[0])), *((vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator*) G__int(libp->para[1]))
, *((vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->insert(*((vector<ddaschannel*,allocator<ddaschannel*> >::iterator*) G__int(libp->para[0])), (vector<ddaschannel*,allocator<ddaschannel*> >::size_type) G__int(libp->para[1])
, libp->para[2].ref ? *(ddaschannel**) libp->para[2].ref : *(ddaschannel**) (void*) (&G__Mlong(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->pop_back();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->erase(*((vector<ddaschannel*,allocator<ddaschannel*> >::iterator*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->erase(*((vector<ddaschannel*,allocator<ddaschannel*> >::iterator*) G__int(libp->para[0])), *((vector<ddaschannel*,allocator<ddaschannel*> >::iterator*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DDASEventDictionary_171_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<ddaschannel*,allocator<ddaschannel*> >*) G__getstructoffset())->clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vector<ddaschannel*,allocator<ddaschannel*> > G__TvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR;
static int G__DDASEventDictionary_171_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vector<ddaschannel*,allocator<ddaschannel*> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vector<ddaschannel*,allocator<ddaschannel*> >*) (soff+(sizeof(vector<ddaschannel*,allocator<ddaschannel*> >)*i)))->~G__TvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vector<ddaschannel*,allocator<ddaschannel*> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vector<ddaschannel*,allocator<ddaschannel*> >*) (soff))->~G__TvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DDASEvent */

/* vector<ddaschannel*,allocator<ddaschannel*> > */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDDASEventDictionary {
 public:
  G__Sizep2memfuncDDASEventDictionary(): p(&G__Sizep2memfuncDDASEventDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDDASEventDictionary::*p)();
};

size_t G__get_sizep2memfuncDDASEventDictionary()
{
  G__Sizep2memfuncDDASEventDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDDASEventDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent))) {
     DDASEvent *G__Lderived;
     G__Lderived=(DDASEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent),G__get_linked_tagnum(&G__DDASEventDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDDASEventDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ddaschannel*>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("value_type",85,G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pointer",85,G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel),256,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reference",85,G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel),1,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel),257,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DDASEvent */
static void G__setup_memvarDDASEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent));
   { DDASEvent *p; p=(DDASEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR),G__defined_typename("vector<ddaschannel*>"),-1,4,"m_data=",0,"Extensible array of primitive  ddaschannel objects");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DDASEventDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* vector<ddaschannel*,allocator<ddaschannel*> > */
static void G__setup_memvarvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   { vector<ddaschannel*,allocator<ddaschannel*> > *p; p=(vector<ddaschannel*,allocator<ddaschannel*> >*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDDASEventDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDDASEvent(void) {
   /* DDASEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent));
   G__memfunc_setup("DDASEvent",798,G__DDASEventDictionary_169_0_1, 105, G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DDASEvent",798,G__DDASEventDictionary_169_0_2, 105, G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent), -1, 0, 1, 1, 1, 0, "u 'DDASEvent' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__DDASEventDictionary_169_0_3, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_DDASEvent), -1, 1, 1, 1, 1, 0, "u 'DDASEvent' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetData",666,G__DDASEventDictionary_169_0_4, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR), G__defined_typename("vector<ddaschannel*>"), 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddChannelData",1340,G__DDASEventDictionary_169_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'ddaschannel' - 0 - channel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNEvents",995,G__DDASEventDictionary_169_0_6, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFirstTime",1207,G__DDASEventDictionary_169_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLastTime",1091,G__DDASEventDictionary_169_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimeWidth",1199,G__DDASEventDictionary_169_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__DDASEventDictionary_169_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DDASEventDictionary_169_0_11, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DDASEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DDASEventDictionary_169_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DDASEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DDASEventDictionary_169_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DDASEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DDASEventDictionary_169_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DDASEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DDASEventDictionary_169_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DDASEventDictionary_169_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DDASEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DDASEventDictionary_169_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DDASEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DDASEventDictionary_169_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DDASEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DDASEventDictionary_169_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DDASEvent::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~DDASEvent", 924, G__DDASEventDictionary_169_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR(void) {
   /* vector<ddaschannel*,allocator<ddaschannel*> > */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR));
   G__memfunc_setup("at",213,G__DDASEventDictionary_171_0_1, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel), G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("at",213,G__DDASEventDictionary_171_0_2, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel), G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("begin",517,G__DDASEventDictionary_171_0_3, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("end",311,G__DDASEventDictionary_171_0_4, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rbegin",631,G__DDASEventDictionary_171_0_5, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR), G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rend",425,G__DDASEventDictionary_171_0_6, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR), G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__DDASEventDictionary_171_0_7, 107, -1, G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("max_size",864,G__DDASEventDictionary_171_0_8, 107, -1, G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__DDASEventDictionary_171_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__DDASEventDictionary_171_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - sz U 'ddaschannel' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("capacity",846,G__DDASEventDictionary_171_0_11, 107, -1, G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("empty",559,G__DDASEventDictionary_171_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__DDASEventDictionary_171_0_13, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel), G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__DDASEventDictionary_171_0_14, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel), G__defined_typename("vector<ddaschannel*,allocator<ddaschannel*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ddaschannel*,allocator<ddaschannel*> >",4306,G__DDASEventDictionary_171_0_15, 105, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ddaschannel*,allocator<ddaschannel*> >",4306,G__DDASEventDictionary_171_0_16, 105, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR), -1, 0, 2, 1, 1, 0, 
"k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n U 'ddaschannel' - 41 '(ddaschannel*)()' value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ddaschannel*,allocator<ddaschannel*> >",4306,G__DDASEventDictionary_171_0_17, 105, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<ddaschannel*,allocator<ddaschannel*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<ddaschannel*,allocator<ddaschannel*> >",4306,G__DDASEventDictionary_171_0_18, 105, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR), -1, 0, 2, 1, 1, 0, 
"u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' 'vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator' 10 - first u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' 'vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__DDASEventDictionary_171_0_19, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<ddaschannel*,allocator<ddaschannel*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reserve",764,G__DDASEventDictionary_171_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("front",553,G__DDASEventDictionary_171_0_21, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("back",401,G__DDASEventDictionary_171_0_22, 85, G__get_linked_tagnum(&G__DDASEventDictionaryLN_ddaschannel), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("push_back",944,G__DDASEventDictionary_171_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "U 'ddaschannel' - 41 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("swap",443,G__DDASEventDictionary_171_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<ddaschannel*,allocator<ddaschannel*> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__DDASEventDictionary_171_0_25, 117, G__get_linked_tagnum(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0, 
"u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' - 0 - position U 'ddaschannel' - 41 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__DDASEventDictionary_171_0_26, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' - 0 - position u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' 'vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator' 10 - first "
"u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' 'vector<ddaschannel*,allocator<ddaschannel*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__DDASEventDictionary_171_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' - 0 - position k - 'vector<ddaschannel*,allocator<ddaschannel*> >::size_type' 0 - n "
"U 'ddaschannel' - 41 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("pop_back",831,G__DDASEventDictionary_171_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__DDASEventDictionary_171_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__DDASEventDictionary_171_0_30, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' - 0 - first u 'vector<ddaschannel*,allocator<ddaschannel*> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clear",519,G__DDASEventDictionary_171_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vector<ddaschannel*,allocator<ddaschannel*> >", 4432, G__DDASEventDictionary_171_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDDASEventDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDDASEventDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDDASEventDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DDASEventDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_ddaschannel = { "ddaschannel" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_DDASEvent = { "DDASEvent" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR = { "vector<ddaschannel*,allocator<ddaschannel*> >" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator = { "vector<ddaschannel*,allocator<ddaschannel*> >::iterator" , 99 , -1 };
G__linked_taginfo G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ddaschannel*,allocator<ddaschannel*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDDASEventDictionary() {
  G__DDASEventDictionaryLN_TClass.tagnum = -1 ;
  G__DDASEventDictionaryLN_TBuffer.tagnum = -1 ;
  G__DDASEventDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__DDASEventDictionaryLN_TObject.tagnum = -1 ;
  G__DDASEventDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_ddaschannel.tagnum = -1 ;
  G__DDASEventDictionaryLN_DDASEvent.tagnum = -1 ;
  G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR.tagnum = -1 ;
  G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator.tagnum = -1 ;
  G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDDASEventDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_ddaschannel);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_DDASEvent),sizeof(DDASEvent),-1,294656,(char*)NULL,G__setup_memvarDDASEvent,G__setup_memfuncDDASEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR),sizeof(vector<ddaschannel*,allocator<ddaschannel*> >),-1,298752,(char*)NULL,G__setup_memvarvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR,G__setup_memfuncvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupDDASEventDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupDDASEventDictionary()");
  G__set_cpp_environmentDDASEventDictionary();
  G__cpp_setup_tagtableDDASEventDictionary();

  G__cpp_setup_inheritanceDDASEventDictionary();

  G__cpp_setup_typetableDDASEventDictionary();

  G__cpp_setup_memvarDDASEventDictionary();

  G__cpp_setup_memfuncDDASEventDictionary();
  G__cpp_setup_globalDDASEventDictionary();
  G__cpp_setup_funcDDASEventDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDDASEventDictionary();
  return;
}
class G__cpp_setup_initDDASEventDictionary {
  public:
    G__cpp_setup_initDDASEventDictionary() { G__add_setup_func("DDASEventDictionary",(G__incsetup)(&G__cpp_setupDDASEventDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDDASEventDictionary() { G__remove_setup_func("DDASEventDictionary"); }
};
G__cpp_setup_initDDASEventDictionary G__cpp_setup_initializerDDASEventDictionary;

