/********************************************************************
* DDASEventDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DDASEventDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDDASEventDictionary();
extern void G__cpp_setup_inheritanceDDASEventDictionary();
extern void G__cpp_setup_typetableDDASEventDictionary();
extern void G__cpp_setup_memvarDDASEventDictionary();
extern void G__cpp_setup_globalDDASEventDictionary();
extern void G__cpp_setup_memfuncDDASEventDictionary();
extern void G__cpp_setup_funcDDASEventDictionary();
extern void G__set_cpp_environmentDDASEventDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DDASEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DDASEventDictionaryLN_TClass;
extern G__linked_taginfo G__DDASEventDictionaryLN_TBuffer;
extern G__linked_taginfo G__DDASEventDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__DDASEventDictionaryLN_TObject;
extern G__linked_taginfo G__DDASEventDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_ddaschannel;
extern G__linked_taginfo G__DDASEventDictionaryLN_DDASEvent;
extern G__linked_taginfo G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR;
extern G__linked_taginfo G__DDASEventDictionaryLN_vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__DDASEventDictionaryLN_reverse_iteratorlEvectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<ddaschannel*,allocator<ddaschannel*> > G__vectorlEddaschannelmUcOallocatorlEddaschannelmUgRsPgR;
