//
// File generated by rootcint at Mon Oct  2 14:08:56 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME LendaFilterDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LendaFilterDictionary.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::FilterDebugInfo FilterDebugInfo;
      #else
      class FilterDebugInfo  {
         public:
         //friend XX;
         double BaseLine; //
         double StandardDev; //
         double BaseLineWindowBegin; //
         double BaseLineWindowEnd; //
         double Threshold; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void FilterDebugInfo_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void FilterDebugInfo_Dictionary();
   static void *new_FilterDebugInfo(void *p = 0);
   static void *newArray_FilterDebugInfo(Long_t size, void *p);
   static void delete_FilterDebugInfo(void *p);
   static void deleteArray_FilterDebugInfo(void *p);
   static void destruct_FilterDebugInfo(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::FilterDebugInfo*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::FilterDebugInfo) == sizeof( ::ROOTShadow::Shadow::FilterDebugInfo));
      ::FilterDebugInfo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::FilterDebugInfo),0);
      static ::ROOT::TGenericClassInfo 
         instance("FilterDebugInfo", "./LendaFilter.hh", 13,
                  typeid(::FilterDebugInfo), ::ROOT::DefineBehavior(ptr, ptr),
                  &FilterDebugInfo_ShowMembers, &FilterDebugInfo_Dictionary, isa_proxy, 4,
                  sizeof(::FilterDebugInfo) );
      instance.SetNew(&new_FilterDebugInfo);
      instance.SetNewArray(&newArray_FilterDebugInfo);
      instance.SetDelete(&delete_FilterDebugInfo);
      instance.SetDeleteArray(&deleteArray_FilterDebugInfo);
      instance.SetDestructor(&destruct_FilterDebugInfo);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::FilterDebugInfo*)
   {
      return GenerateInitInstanceLocal((::FilterDebugInfo*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FilterDebugInfo*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void FilterDebugInfo_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::FilterDebugInfo*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void LendaFilter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_LendaFilter(void *p = 0);
   static void *newArray_LendaFilter(Long_t size, void *p);
   static void delete_LendaFilter(void *p);
   static void deleteArray_LendaFilter(void *p);
   static void destruct_LendaFilter(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::LendaFilter*)
   {
      ::LendaFilter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::LendaFilter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("LendaFilter", ::LendaFilter::Class_Version(), "./LendaFilter.hh", 23,
                  typeid(::LendaFilter), ::ROOT::DefineBehavior(ptr, ptr),
                  &::LendaFilter::Dictionary, isa_proxy, 4,
                  sizeof(::LendaFilter) );
      instance.SetNew(&new_LendaFilter);
      instance.SetNewArray(&newArray_LendaFilter);
      instance.SetDelete(&delete_LendaFilter);
      instance.SetDeleteArray(&deleteArray_LendaFilter);
      instance.SetDestructor(&destruct_LendaFilter);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::LendaFilter*)
   {
      return GenerateInitInstanceLocal((::LendaFilter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::LendaFilter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr LendaFilter::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *LendaFilter::Class_Name()
{
   return "LendaFilter";
}

//______________________________________________________________________________
const char *LendaFilter::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::LendaFilter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int LendaFilter::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::LendaFilter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void LendaFilter::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::LendaFilter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *LendaFilter::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::LendaFilter*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void LendaFilter::Streamer(TBuffer &R__b)
{
   // Stream an object of class LendaFilter.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(LendaFilter::Class(),this);
   } else {
      R__b.WriteClassBuffer(LendaFilter::Class(),this);
   }
}

//______________________________________________________________________________
void LendaFilter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class LendaFilter.
      TClass *R__cl = ::LendaFilter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numOfBadFits", &numOfBadFits);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_LendaFilter(void *p) {
      return  p ? new(p) ::LendaFilter : new ::LendaFilter;
   }
   static void *newArray_LendaFilter(Long_t nElements, void *p) {
      return p ? new(p) ::LendaFilter[nElements] : new ::LendaFilter[nElements];
   }
   // Wrapper around operator delete
   static void delete_LendaFilter(void *p) {
      delete ((::LendaFilter*)p);
   }
   static void deleteArray_LendaFilter(void *p) {
      delete [] ((::LendaFilter*)p);
   }
   static void destruct_LendaFilter(void *p) {
      typedef ::LendaFilter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::LendaFilter

//______________________________________________________________________________
namespace ROOTDict {
   void FilterDebugInfo_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class FilterDebugInfo.
      typedef ::ROOTShadow::Shadow::FilterDebugInfo ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::FilterDebugInfo*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BaseLine", &sobj->BaseLine);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "StandardDev", &sobj->StandardDev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BaseLineWindowBegin", &sobj->BaseLineWindowBegin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BaseLineWindowEnd", &sobj->BaseLineWindowEnd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Threshold", &sobj->Threshold);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_FilterDebugInfo(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::FilterDebugInfo : new ::FilterDebugInfo;
   }
   static void *newArray_FilterDebugInfo(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::FilterDebugInfo[nElements] : new ::FilterDebugInfo[nElements];
   }
   // Wrapper around operator delete
   static void delete_FilterDebugInfo(void *p) {
      delete ((::FilterDebugInfo*)p);
   }
   static void deleteArray_FilterDebugInfo(void *p) {
      delete [] ((::FilterDebugInfo*)p);
   }
   static void destruct_FilterDebugInfo(void *p) {
      typedef ::FilterDebugInfo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::FilterDebugInfo

/********************************************************
* LendaFilterDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableLendaFilterDictionary();

extern "C" void G__set_cpp_environmentLendaFilterDictionary() {
  G__cpp_reset_tagtableLendaFilterDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevLendaFilterDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FilterDebugInfo */
// automatic default constructor
static int G__LendaFilterDictionary_196_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FilterDebugInfo *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FilterDebugInfo[n];
     } else {
       p = new((void*) gvp) FilterDebugInfo[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FilterDebugInfo;
     } else {
       p = new((void*) gvp) FilterDebugInfo;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LendaFilterDictionary_196_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   FilterDebugInfo* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new FilterDebugInfo(*(FilterDebugInfo*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FilterDebugInfo G__TFilterDebugInfo;
static int G__LendaFilterDictionary_196_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FilterDebugInfo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FilterDebugInfo*) (soff+(sizeof(FilterDebugInfo)*i)))->~G__TFilterDebugInfo();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FilterDebugInfo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FilterDebugInfo*) (soff))->~G__TFilterDebugInfo();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LendaFilterDictionary_196_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FilterDebugInfo* dest = (FilterDebugInfo*) G__getstructoffset();
   *dest = *(FilterDebugInfo*) libp->para[0].ref;
   const FilterDebugInfo& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* LendaFilter */
static int G__LendaFilterDictionary_197_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LendaFilter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new LendaFilter[n];
     } else {
       p = new((void*) gvp) LendaFilter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new LendaFilter;
     } else {
       p = new((void*) gvp) LendaFilter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaFilter*) G__getstructoffset())->FastFilter(*(vector<UShort_t>*) libp->para[0].ref, *(vector<Double_t>*) libp->para[1].ref
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaFilter*) G__getstructoffset())->FastFilterOp(*(vector<UShort_t>*) libp->para[0].ref, *(vector<Double_t>*) libp->para[1].ref
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaFilter*) G__getstructoffset())->FastFilterFull(*(vector<UShort_t>*) libp->para[0].ref, *(vector<Double_t>*) libp->para[1].ref
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->CFD(*(vector<Double_t>*) libp->para[0].ref, (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->CFDOp(*(vector<Double_t>*) libp->para[0].ref, (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroCrossing(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetAllZeroCrossings(*(vector<Double_t>*) libp->para[0].ref);
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroCrossingImproved(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroCrossingImprovedRMD(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroCrossingOp(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroCubic(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroCubicRMD(*(vector<Double_t>*) libp->para[0].ref, *(int*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetZeroFitCubic(*(vector<Double_t>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->DoMatrixInversionAlgorithm(*(vector<Double_t>*) libp->para[0].ref, (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetMatrixInversionAlgorithmCoeffients(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1]));
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->fitTrace(*(vector<UShort_t>*) libp->para[0].ref, (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetEnergyOld(*(vector<UShort_t>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetEnergy(*(vector<UShort_t>*) libp->para[0].ref, (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetEnergyRMD(*(vector<UShort_t>*) libp->para[0].ref, (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 6:
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetEnergyHighRate(*(vector<UShort_t>*) libp->para[0].ref, *(vector<Int_t>*) libp->para[1].ref
, *(vector<Double_t>*) libp->para[2].ref, *(Double_t*) G__Doubleref(&libp->para[3])
, *(Int_t*) G__Intref(&libp->para[4]), (FilterDebugInfo*) G__int(libp->para[5]));
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   case 5:
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetEnergyHighRate(*(vector<UShort_t>*) libp->para[0].ref, *(vector<Int_t>*) libp->para[1].ref
, *(vector<Double_t>*) libp->para[2].ref, *(Double_t*) G__Doubleref(&libp->para[3])
, *(Int_t*) G__Intref(&libp->para[4]));
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Int_t>* pobj;
         vector<Int_t> xobj = ((LendaFilter*) G__getstructoffset())->GetPulseHeightHighRate(*(vector<UShort_t>*) libp->para[0].ref, *(vector<Int_t>*) libp->para[1].ref);
         pobj = new vector<Int_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetZeroCrossingHighRate(*(vector<Double_t>*) libp->para[0].ref, *(vector<Int_t>*) libp->para[1].ref);
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetZeroCrossingCubicHighRate(*(vector<Double_t>*) libp->para[0].ref, *(vector<Int_t>*) libp->para[1].ref);
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetGate(*(vector<UShort_t>*) libp->para[0].ref, (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetGateRMD(*(vector<UShort_t>*) libp->para[0].ref, *(int*) G__Intref(&libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetLeadingEdge(*(vector<UShort_t>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetFilterEnergy(*(vector<UShort_t>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((LendaFilter*) G__getstructoffset())->GetMaxPulseHeight(*(vector<UShort_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((LendaFilter*) G__getstructoffset())->GetMaxPulseHeight(*(vector<Double_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetMaxPulseHeightBaseline(*(vector<UShort_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetPulseComplete(*(vector<UShort_t>*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2]), *(Double_t*) G__Doubleref(&libp->para[3])
, *(Double_t*) G__Doubleref(&libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->getFunc(*((TMatrixT<Double_t>*) G__int(libp->para[0])), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->getFunc(*(vector<double>*) libp->para[0].ref, (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((LendaFilter*) G__getstructoffset())->GetStartForPulseShape((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((LendaFilter*) G__getstructoffset())->CalculateCFD(*((vector<UShort_t>*) G__int(libp->para[0])), *(vector<Double_t>*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Double_t>* pobj;
         vector<Double_t> xobj = ((LendaFilter*) G__getstructoffset())->GetNewFirmwareCFD(*(vector<UShort_t>*) libp->para[0].ref, (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4]));
         pobj = new vector<Double_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((LendaFilter*) G__getstructoffset())->GetNewFirmwareCFDWeight((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) LendaFilter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LendaFilter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) LendaFilter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      LendaFilter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LendaFilter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LendaFilter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) LendaFilter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LendaFilter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LendaFilterDictionary_197_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) LendaFilter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LendaFilterDictionary_197_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   LendaFilter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new LendaFilter(*(LendaFilter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef LendaFilter G__TLendaFilter;
static int G__LendaFilterDictionary_197_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (LendaFilter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((LendaFilter*) (soff+(sizeof(LendaFilter)*i)))->~G__TLendaFilter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (LendaFilter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((LendaFilter*) (soff))->~G__TLendaFilter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LendaFilterDictionary_197_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LendaFilter* dest = (LendaFilter*) G__getstructoffset();
   *dest = *(LendaFilter*) libp->para[0].ref;
   const LendaFilter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FilterDebugInfo */

/* LendaFilter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncLendaFilterDictionary {
 public:
  G__Sizep2memfuncLendaFilterDictionary(): p(&G__Sizep2memfuncLendaFilterDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncLendaFilterDictionary::*p)();
};

size_t G__get_sizep2memfuncLendaFilterDictionary()
{
  G__Sizep2memfuncLendaFilterDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceLendaFilterDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter))) {
     LendaFilter *G__Lderived;
     G__Lderived=(LendaFilter*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter),G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableLendaFilterDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FilterDebugInfo */
static void G__setup_memvarFilterDebugInfo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo));
   { FilterDebugInfo *p; p=(FilterDebugInfo*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->BaseLine)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"BaseLine=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->StandardDev)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"StandardDev=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->BaseLineWindowBegin)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"BaseLineWindowBegin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->BaseLineWindowEnd)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"BaseLineWindowEnd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Threshold)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Threshold=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* LendaFilter */
static void G__setup_memvarLendaFilter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter));
   { LendaFilter *p; p=(LendaFilter*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->numOfBadFits)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"numOfBadFits=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarLendaFilterDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFilterDebugInfo(void) {
   /* FilterDebugInfo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo));
   // automatic default constructor
   G__memfunc_setup("FilterDebugInfo", 1497, G__LendaFilterDictionary_196_0_1, (int) ('i'), G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("FilterDebugInfo", 1497, G__LendaFilterDictionary_196_0_2, (int) ('i'), G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo), -1, 0, 1, 1, 1, 0, "u 'FilterDebugInfo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~FilterDebugInfo", 1623, G__LendaFilterDictionary_196_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LendaFilterDictionary_196_0_4, (int) ('u'), G__get_linked_tagnum(&G__LendaFilterDictionaryLN_FilterDebugInfo), -1, 1, 1, 1, 1, 0, "u 'FilterDebugInfo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncLendaFilter(void) {
   /* LendaFilter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter));
   G__memfunc_setup("LendaFilter",1098,G__LendaFilterDictionary_197_0_1, 105, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FastFilter",1012,G__LendaFilterDictionary_197_0_2, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - thisEventsFF "
"d - 'Double_t' 0 - FL d - 'Double_t' 0 - FG", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FastFilterOp",1203,G__LendaFilterDictionary_197_0_3, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - thisEventsFF "
"d - 'Double_t' 0 - FL d - 'Double_t' 0 - FG", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FastFilterFull",1415,G__LendaFilterDictionary_197_0_4, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - thisEventsFF "
"d - 'Double_t' 0 - FL d - 'Double_t' 0 - FG "
"d - 'Double_t' 0 - decayTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CFD",205,G__LendaFilterDictionary_197_0_5, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 3, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - d - 'Double_t' 0 - - "
"d - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CFDOp",396,G__LendaFilterDictionary_197_0_6, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 3, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - d - 'Double_t' 0 - - "
"d - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCrossing",1544,G__LendaFilterDictionary_197_0_7, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - i - 'Int_t' 1 - - "
"d - 'Double_t' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAllZeroCrossings",1940,G__LendaFilterDictionary_197_0_8, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCrossingImproved",2382,G__LendaFilterDictionary_197_0_9, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - i - 'Int_t' 1 - - "
"d - 'Double_t' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCrossingImprovedRMD",2609,G__LendaFilterDictionary_197_0_10, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - i - 'Int_t' 1 - - "
"d - 'Double_t' 1 - -", "/<Extracts zero-crossing CFD with a different search algorithm, better suited for slow signals ", (void*) NULL, 0);
   G__memfunc_setup("GetZeroCrossingOp",1735,G__LendaFilterDictionary_197_0_11, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - i - 'Int_t' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCubic",1190,G__LendaFilterDictionary_197_0_12, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - i - 'Int_t' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCubicRMD",1417,G__LendaFilterDictionary_197_0_13, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - - i - - 1 - -", "/<Extracts zero-crossing CFD (cubic-fit) with a different search algorithm, better suited for slow signals  ", (void*) NULL, 0);
   G__memfunc_setup("GetZeroFitCubic",1481,G__LendaFilterDictionary_197_0_14, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoMatrixInversionAlgorithm",2700,G__LendaFilterDictionary_197_0_15, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 11 - CFD i - 'Int_t' 0 - Spot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMatrixInversionAlgorithmCoeffients",3839,G__LendaFilterDictionary_197_0_16, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 11 - CFD i - 'Int_t' 1 - Spot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fitTrace",818,G__LendaFilterDictionary_197_0_17, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - - d - 'Double_t' 0 - - "
"d - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyOld",1193,G__LendaFilterDictionary_197_0_18, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__LendaFilterDictionary_197_0_19, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - 'Int_t' 0 - MaxSpot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyRMD",1133,G__LendaFilterDictionary_197_0_20, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - 'Int_t' 0 - MaxSpot", "/<Integrates trace around maximum using asymmetric limits (better suited for slow signals with long decay tails)", (void*) NULL, 0);
   G__memfunc_setup("GetEnergyHighRate",1686,G__LendaFilterDictionary_197_0_21, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 6, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 11 - trace u 'vector<int,allocator<int> >' 'vector<Int_t>' 1 - PeakSpots "
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - theUnderShoots d - 'Double_t' 1 - MaxValueOut "
"i - 'Int_t' 1 - MaxIndexOut U 'FilterDebugInfo' - 0 '0' info", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPulseHeightHighRate",2190,G__LendaFilterDictionary_197_0_22, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<Int_t>"), 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 11 - trace u 'vector<int,allocator<int> >' 'vector<Int_t>' 11 - PeakSpots", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCrossingHighRate",2324,G__LendaFilterDictionary_197_0_23, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 11 - CFD u 'vector<int,allocator<int> >' 'vector<Int_t>' 11 - PeakSpots", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZeroCrossingCubicHighRate",2810,G__LendaFilterDictionary_197_0_24, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 11 - CFD u 'vector<int,allocator<int> >' 'vector<Int_t>' 11 - PeakSpots", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGate",673,G__LendaFilterDictionary_197_0_25, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - - 0 - start "
"i - - 0 - L", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGateRMD",900,G__LendaFilterDictionary_197_0_26, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - - 1 - start "
"i - - 0 - L", "/<Integrates trace from \"raising\" point (calculated from trace derivative) over range L", (void*) NULL, 0);
   G__memfunc_setup("GetLeadingEdge",1353,G__LendaFilterDictionary_197_0_27, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace", "/<Calculates Leading-edge time", (void*) NULL, 0);
   G__memfunc_setup("GetFilterEnergy",1520,G__LendaFilterDictionary_197_0_28, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace", "/<Calculates energy from trace-analysis using trapezoidal-filter (see. Tan et al., IEEE trans. of nucl. sci., 51, 1541 (2004) )", (void*) NULL, 0);
   G__memfunc_setup("GetMaxPulseHeight",1704,G__LendaFilterDictionary_197_0_29, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - 'Int_t' 1 - MaxSpot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMaxPulseHeight",1704,G__LendaFilterDictionary_197_0_30, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - trace i - 'Int_t' 1 - MaxSpot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMaxPulseHeightBaseline",2507,G__LendaFilterDictionary_197_0_31, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - 'Int_t' 1 - MaxSpot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPulseComplete",1634,G__LendaFilterDictionary_197_0_32, 100, -1, G__defined_typename("Double_t"), 0, 5, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 1 - trace i - 'Int_t' 1 - MaxSpot "
"d - 'Double_t' 1 - rising d - 'Double_t' 1 - background "
"d - 'Double_t' 1 - noise", "/<Takes trace and calculates pulse-hight (minus baseline), rising time, baseline, and noise level ", (void*) NULL, 0);
   G__memfunc_setup("getFunc",716,G__LendaFilterDictionary_197_0_33, 100, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMatrixT<double>' 'TMatrixT<Double_t>' 0 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getFunc",716,G__LendaFilterDictionary_197_0_34, 100, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<double>' 1 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStartForPulseShape",2127,G__LendaFilterDictionary_197_0_35, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - MaxSpot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateCFD",1115,G__LendaFilterDictionary_197_0_36, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 0 - trace u 'vector<double,allocator<double> >' 'vector<Double_t>' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNewFirmwareCFD",1620,G__LendaFilterDictionary_197_0_37, 117, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<Double_t>"), 0, 5, 1, 1, 0, 
"u 'vector<unsigned short,allocator<unsigned short> >' 'vector<UShort_t>' 11 - trace i - 'Int_t' 0 - FL "
"i - 'Int_t' 0 - FG i - 'Int_t' 0 - d "
"i - 'Int_t' 0 - w", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNewFirmwareCFDWeight",2236,G__LendaFilterDictionary_197_0_38, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - CFDScaleFactor", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__LendaFilterDictionary_197_0_39, 85, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&LendaFilter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__LendaFilterDictionary_197_0_40, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&LendaFilter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__LendaFilterDictionary_197_0_41, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&LendaFilter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__LendaFilterDictionary_197_0_42, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&LendaFilter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__LendaFilterDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__LendaFilterDictionary_197_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__LendaFilterDictionary_197_0_47, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&LendaFilter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__LendaFilterDictionary_197_0_48, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&LendaFilter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__LendaFilterDictionary_197_0_49, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&LendaFilter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__LendaFilterDictionary_197_0_50, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&LendaFilter::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("LendaFilter", 1098, G__LendaFilterDictionary_197_0_51, (int) ('i'), G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter), -1, 0, 1, 1, 1, 0, "u 'LendaFilter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~LendaFilter", 1224, G__LendaFilterDictionary_197_0_52, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LendaFilterDictionary_197_0_53, (int) ('u'), G__get_linked_tagnum(&G__LendaFilterDictionaryLN_LendaFilter), -1, 1, 1, 1, 1, 0, "u 'LendaFilter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncLendaFilterDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalLendaFilterDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcLendaFilterDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__LendaFilterDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_FilterDebugInfo = { "FilterDebugInfo" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_LendaFilter = { "LendaFilter" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LendaFilterDictionaryLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableLendaFilterDictionary() {
  G__LendaFilterDictionaryLN_TClass.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TBuffer.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TObject.tagnum = -1 ;
  G__LendaFilterDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_FilterDebugInfo.tagnum = -1 ;
  G__LendaFilterDictionaryLN_LendaFilter.tagnum = -1 ;
  G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LendaFilterDictionaryLN_TMatrixTlEdoublegR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableLendaFilterDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TVectorTlEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_FilterDebugInfo),sizeof(FilterDebugInfo),-1,262144,(char*)NULL,G__setup_memvarFilterDebugInfo,G__setup_memfuncFilterDebugInfo);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_LendaFilter),sizeof(LendaFilter),-1,292096,(char*)NULL,G__setup_memvarLendaFilter,G__setup_memfuncLendaFilter);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LendaFilterDictionaryLN_TMatrixTlEdoublegR);
}
extern "C" void G__cpp_setupLendaFilterDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupLendaFilterDictionary()");
  G__set_cpp_environmentLendaFilterDictionary();
  G__cpp_setup_tagtableLendaFilterDictionary();

  G__cpp_setup_inheritanceLendaFilterDictionary();

  G__cpp_setup_typetableLendaFilterDictionary();

  G__cpp_setup_memvarLendaFilterDictionary();

  G__cpp_setup_memfuncLendaFilterDictionary();
  G__cpp_setup_globalLendaFilterDictionary();
  G__cpp_setup_funcLendaFilterDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncLendaFilterDictionary();
  return;
}
class G__cpp_setup_initLendaFilterDictionary {
  public:
    G__cpp_setup_initLendaFilterDictionary() { G__add_setup_func("LendaFilterDictionary",(G__incsetup)(&G__cpp_setupLendaFilterDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initLendaFilterDictionary() { G__remove_setup_func("LendaFilterDictionary"); }
};
G__cpp_setup_initLendaFilterDictionary G__cpp_setup_initializerLendaFilterDictionary;

