/********************************************************************
* LendaFilterDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LendaFilterDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLendaFilterDictionary();
extern void G__cpp_setup_inheritanceLendaFilterDictionary();
extern void G__cpp_setup_typetableLendaFilterDictionary();
extern void G__cpp_setup_memvarLendaFilterDictionary();
extern void G__cpp_setup_globalLendaFilterDictionary();
extern void G__cpp_setup_memfuncLendaFilterDictionary();
extern void G__cpp_setup_funcLendaFilterDictionary();
extern void G__set_cpp_environmentLendaFilterDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LendaFilter.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LendaFilterDictionaryLN_TClass;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TBuffer;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TObject;
extern G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_FilterDebugInfo;
extern G__linked_taginfo G__LendaFilterDictionaryLN_LendaFilter;
extern G__linked_taginfo G__LendaFilterDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LendaFilterDictionaryLN_TMatrixTlEdoublegR;

/* STUB derived class for protected member access */
