/********************************************************************
* S800CalcDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S800CalcDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS800CalcDictionary();
extern void G__cpp_setup_inheritanceS800CalcDictionary();
extern void G__cpp_setup_typetableS800CalcDictionary();
extern void G__cpp_setup_memvarS800CalcDictionary();
extern void G__cpp_setup_globalS800CalcDictionary();
extern void G__cpp_setup_memfuncS800CalcDictionary();
extern void G__cpp_setup_funcS800CalcDictionary();
extern void G__set_cpp_environmentS800CalcDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "S800Calc.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S800CalcDictionaryLN_TClass;
extern G__linked_taginfo G__S800CalcDictionaryLN_TBuffer;
extern G__linked_taginfo G__S800CalcDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__S800CalcDictionaryLN_TObject;
extern G__linked_taginfo G__S800CalcDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_S800;
extern G__linked_taginfo G__S800CalcDictionaryLN_S800Calibration;
extern G__linked_taginfo G__S800CalcDictionaryLN_CRDC;
extern G__linked_taginfo G__S800CalcDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalcDictionaryLN_TOF;
extern G__linked_taginfo G__S800CalcDictionaryLN_MultiHitTOF;
extern G__linked_taginfo G__S800CalcDictionaryLN_SCINT;
extern G__linked_taginfo G__S800CalcDictionaryLN_HODOSCOPE;
extern G__linked_taginfo G__S800CalcDictionaryLN_IC;
extern G__linked_taginfo G__S800CalcDictionaryLN_Trigger;
extern G__linked_taginfo G__S800CalcDictionaryLN_S800Calc;

/* STUB derived class for protected member access */
