/********************************************************************
* S800SettingsDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S800SettingsDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS800SettingsDictionary();
extern void G__cpp_setup_inheritanceS800SettingsDictionary();
extern void G__cpp_setup_typetableS800SettingsDictionary();
extern void G__cpp_setup_memvarS800SettingsDictionary();
extern void G__cpp_setup_globalS800SettingsDictionary();
extern void G__cpp_setup_memfuncS800SettingsDictionary();
extern void G__cpp_setup_funcS800SettingsDictionary();
extern void G__set_cpp_environmentS800SettingsDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "S800Settings.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S800SettingsDictionaryLN_TClass;
extern G__linked_taginfo G__S800SettingsDictionaryLN_TBuffer;
extern G__linked_taginfo G__S800SettingsDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__S800SettingsDictionaryLN_TObject;
extern G__linked_taginfo G__S800SettingsDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_string;
extern G__linked_taginfo G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800SettingsDictionaryLN_S800Settings;

/* STUB derived class for protected member access */
