//
// File generated by rootcint at Mon Oct  2 14:08:41 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME S800SettingsDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "S800SettingsDictionary.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void S800Settings_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_S800Settings(void *p = 0);
   static void *newArray_S800Settings(Long_t size, void *p);
   static void delete_S800Settings(void *p);
   static void deleteArray_S800Settings(void *p);
   static void destruct_S800Settings(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::S800Settings*)
   {
      ::S800Settings *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::S800Settings >(0);
      static ::ROOT::TGenericClassInfo 
         instance("S800Settings", ::S800Settings::Class_Version(), "./S800Settings.hh", 12,
                  typeid(::S800Settings), ::ROOT::DefineBehavior(ptr, ptr),
                  &::S800Settings::Dictionary, isa_proxy, 4,
                  sizeof(::S800Settings) );
      instance.SetNew(&new_S800Settings);
      instance.SetNewArray(&newArray_S800Settings);
      instance.SetDelete(&delete_S800Settings);
      instance.SetDeleteArray(&deleteArray_S800Settings);
      instance.SetDestructor(&destruct_S800Settings);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::S800Settings*)
   {
      return GenerateInitInstanceLocal((::S800Settings*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::S800Settings*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr S800Settings::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *S800Settings::Class_Name()
{
   return "S800Settings";
}

//______________________________________________________________________________
const char *S800Settings::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::S800Settings*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int S800Settings::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::S800Settings*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void S800Settings::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::S800Settings*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *S800Settings::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::S800Settings*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void S800Settings::Streamer(TBuffer &R__b)
{
   // Stream an object of class S800Settings.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(S800Settings::Class(),this);
   } else {
      R__b.WriteClassBuffer(S800Settings::Class(),this);
   }
}

//______________________________________________________________________________
void S800Settings::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class S800Settings.
      TClass *R__cl = ::S800Settings::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fInputFile", (void*)&fInputFile);
      R__insp.InspectMember("string", (void*)&fInputFile, "fInputFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCalFile", (void*)&fCalFile);
      R__insp.InspectMember("string", (void*)&fCalFile, "fCalFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPedestalFile", (void*)&fPedestalFile);
      R__insp.InspectMember("string", (void*)&fPedestalFile, "fPedestalFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBadFile", (void*)&fBadFile);
      R__insp.InspectMember("string", (void*)&fBadFile, "fBadFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCalFileIC", (void*)&fCalFileIC);
      R__insp.InspectMember("string", (void*)&fCalFileIC, "fCalFileIC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXFit", &fXFit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXFitFunc", &fXFitFunc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fxOffset[2]", fxOffset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fxSlope[2]", fxSlope);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fyOffset[2]", fyOffset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fySlope[2]", fySlope);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_S800Settings(void *p) {
      return  p ? new(p) ::S800Settings : new ::S800Settings;
   }
   static void *newArray_S800Settings(Long_t nElements, void *p) {
      return p ? new(p) ::S800Settings[nElements] : new ::S800Settings[nElements];
   }
   // Wrapper around operator delete
   static void delete_S800Settings(void *p) {
      delete ((::S800Settings*)p);
   }
   static void deleteArray_S800Settings(void *p) {
      delete [] ((::S800Settings*)p);
   }
   static void destruct_S800Settings(void *p) {
      typedef ::S800Settings current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::S800Settings

/********************************************************
* S800SettingsDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableS800SettingsDictionary();

extern "C" void G__set_cpp_environmentS800SettingsDictionary() {
  G__cpp_reset_tagtableS800SettingsDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevS800SettingsDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* S800Settings */
static int G__S800SettingsDictionary_443_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   S800Settings* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new S800Settings[n];
     } else {
       p = new((void*) gvp) S800Settings[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new S800Settings;
     } else {
       p = new((void*) gvp) S800Settings;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   S800Settings* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new S800Settings((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) S800Settings((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Settings*) G__getstructoffset())->ReadSettings();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Settings*) G__getstructoffset())->SetFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((S800Settings*) G__getstructoffset())->InputFile();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((S800Settings*) G__getstructoffset())->XFit());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((S800Settings*) G__getstructoffset())->XFitFunc());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Settings*) G__getstructoffset())->XOffset((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Settings*) G__getstructoffset())->XSlope((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Settings*) G__getstructoffset())->YOffset((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Settings*) G__getstructoffset())->YSlope((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((S800Settings*) G__getstructoffset())->CalFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((S800Settings*) G__getstructoffset())->PedestalFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((S800Settings*) G__getstructoffset())->BadFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((S800Settings*) G__getstructoffset())->CalFileIC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) S800Settings::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) S800Settings::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) S800Settings::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      S800Settings::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Settings*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) S800Settings::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) S800Settings::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) S800Settings::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800SettingsDictionary_443_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) S800Settings::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__S800SettingsDictionary_443_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   S800Settings* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new S800Settings(*(S800Settings*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef S800Settings G__TS800Settings;
static int G__S800SettingsDictionary_443_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (S800Settings*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((S800Settings*) (soff+(sizeof(S800Settings)*i)))->~G__TS800Settings();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (S800Settings*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((S800Settings*) (soff))->~G__TS800Settings();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__S800SettingsDictionary_443_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   S800Settings* dest = (S800Settings*) G__getstructoffset();
   *dest = *(S800Settings*) libp->para[0].ref;
   const S800Settings& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* S800Settings */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncS800SettingsDictionary {
 public:
  G__Sizep2memfuncS800SettingsDictionary(): p(&G__Sizep2memfuncS800SettingsDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncS800SettingsDictionary::*p)();
};

size_t G__get_sizep2memfuncS800SettingsDictionary()
{
  G__Sizep2memfuncS800SettingsDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceS800SettingsDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings))) {
     S800Settings *G__Lderived;
     G__Lderived=(S800Settings*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings),G__get_linked_tagnum(&G__S800SettingsDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableS800SettingsDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* S800Settings */
static void G__setup_memvarS800Settings(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings));
   { S800Settings *p; p=(S800Settings*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_string),-1,-1,2,"fInputFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_string),-1,-1,2,"fCalFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_string),-1,-1,2,"fPedestalFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_string),-1,-1,2,"fBadFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_string),-1,-1,2,"fCalFileIC=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fXFit=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fXFitFunc=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fxOffset[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fxSlope[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fyOffset[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fySlope[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__S800SettingsDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarS800SettingsDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncS800Settings(void) {
   /* S800Settings */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings));
   G__memfunc_setup("S800Settings",1084,G__S800SettingsDictionary_443_0_1, 105, G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("S800Settings",1084,G__S800SettingsDictionary_443_0_2, 105, G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings), -1, 0, 1, 1, 1, 0, "C - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadSettings",1229,G__S800SettingsDictionary_443_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFile",684,G__S800SettingsDictionary_443_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InputFile",912,G__S800SettingsDictionary_443_0_5, 117, G__get_linked_tagnum(&G__S800SettingsDictionaryLN_string), -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("XFit",379,G__S800SettingsDictionary_443_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("XFitFunc",775,G__S800SettingsDictionary_443_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("XOffset",703,G__S800SettingsDictionary_443_0_8, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("XSlope",603,G__S800SettingsDictionary_443_0_9, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("YOffset",704,G__S800SettingsDictionary_443_0_10, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("YSlope",604,G__S800SettingsDictionary_443_0_11, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalFile",656,G__S800SettingsDictionary_443_0_12, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PedestalFile",1202,G__S800SettingsDictionary_443_0_13, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BadFile",647,G__S800SettingsDictionary_443_0_14, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalFileIC",796,G__S800SettingsDictionary_443_0_15, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__S800SettingsDictionary_443_0_16, 85, G__get_linked_tagnum(&G__S800SettingsDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&S800Settings::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__S800SettingsDictionary_443_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&S800Settings::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__S800SettingsDictionary_443_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&S800Settings::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__S800SettingsDictionary_443_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&S800Settings::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__S800SettingsDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__S800SettingsDictionary_443_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__S800SettingsDictionary_443_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&S800Settings::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__S800SettingsDictionary_443_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&S800Settings::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__S800SettingsDictionary_443_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&S800Settings::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__S800SettingsDictionary_443_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&S800Settings::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("S800Settings", 1084, G__S800SettingsDictionary_443_0_28, (int) ('i'), G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings), -1, 0, 1, 1, 1, 0, "u 'S800Settings' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~S800Settings", 1210, G__S800SettingsDictionary_443_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__S800SettingsDictionary_443_0_30, (int) ('u'), G__get_linked_tagnum(&G__S800SettingsDictionaryLN_S800Settings), -1, 1, 1, 1, 1, 0, "u 'S800Settings' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncS800SettingsDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalS800SettingsDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcS800SettingsDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__S800SettingsDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800SettingsDictionaryLN_S800Settings = { "S800Settings" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableS800SettingsDictionary() {
  G__S800SettingsDictionaryLN_TClass.tagnum = -1 ;
  G__S800SettingsDictionaryLN_TBuffer.tagnum = -1 ;
  G__S800SettingsDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__S800SettingsDictionaryLN_TObject.tagnum = -1 ;
  G__S800SettingsDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_string.tagnum = -1 ;
  G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800SettingsDictionaryLN_S800Settings.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableS800SettingsDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_string);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__S800SettingsDictionaryLN_S800Settings),sizeof(S800Settings),-1,324864,(char*)NULL,G__setup_memvarS800Settings,G__setup_memfuncS800Settings);
}
extern "C" void G__cpp_setupS800SettingsDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupS800SettingsDictionary()");
  G__set_cpp_environmentS800SettingsDictionary();
  G__cpp_setup_tagtableS800SettingsDictionary();

  G__cpp_setup_inheritanceS800SettingsDictionary();

  G__cpp_setup_typetableS800SettingsDictionary();

  G__cpp_setup_memvarS800SettingsDictionary();

  G__cpp_setup_memfuncS800SettingsDictionary();
  G__cpp_setup_globalS800SettingsDictionary();
  G__cpp_setup_funcS800SettingsDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncS800SettingsDictionary();
  return;
}
class G__cpp_setup_initS800SettingsDictionary {
  public:
    G__cpp_setup_initS800SettingsDictionary() { G__add_setup_func("S800SettingsDictionary",(G__incsetup)(&G__cpp_setupS800SettingsDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initS800SettingsDictionary() { G__remove_setup_func("S800SettingsDictionary"); }
};
G__cpp_setup_initS800SettingsDictionary G__cpp_setup_initializerS800SettingsDictionary;

