//
// File generated by rootcint at Mon Oct  2 14:08:42 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME S800CalibrationDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "S800CalibrationDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::S800Calibration S800Calibration;
      #else
      class S800Calibration  {
         public:
         //friend XX;
         ::S800Settings* fSett; //
         vector< vector< float, allocator< float >  >  > fped; //
         vector< vector< float, allocator< float >  >  > fslope; //
         vector< vector< float, allocator< float >  >  > foffset; //
         vector< vector< int, allocator< int >  >  > fbad; //
         vector< Float_t > fcrdccal; //
         short fts800; //
         vector< Float_t > fICoffset; //
         vector< Float_t > fICslope; //
         float fde_slope; //
         float fde_offset; //
         ::CRDC fcrdc; //
         ::TOF ftof; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void S800Calibration_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void S800Calibration_Dictionary();
   static void *new_S800Calibration(void *p = 0);
   static void *newArray_S800Calibration(Long_t size, void *p);
   static void delete_S800Calibration(void *p);
   static void deleteArray_S800Calibration(void *p);
   static void destruct_S800Calibration(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::S800Calibration*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::S800Calibration) == sizeof( ::ROOTShadow::Shadow::S800Calibration));
      ::S800Calibration *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::S800Calibration),0);
      static ::ROOT::TGenericClassInfo 
         instance("S800Calibration", "./S800Calibration.hh", 28,
                  typeid(::S800Calibration), ::ROOT::DefineBehavior(ptr, ptr),
                  &S800Calibration_ShowMembers, &S800Calibration_Dictionary, isa_proxy, 4,
                  sizeof(::S800Calibration) );
      instance.SetNew(&new_S800Calibration);
      instance.SetNewArray(&newArray_S800Calibration);
      instance.SetDelete(&delete_S800Calibration);
      instance.SetDeleteArray(&deleteArray_S800Calibration);
      instance.SetDestructor(&destruct_S800Calibration);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::S800Calibration*)
   {
      return GenerateInitInstanceLocal((::S800Calibration*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::S800Calibration*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void S800Calibration_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::S800Calibration*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void S800Calibration_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class S800Calibration.
      typedef ::ROOTShadow::Shadow::S800Calibration ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::S800Calibration*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fSett", &sobj->fSett);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fped", (void*)&sobj->fped);
      R__insp.InspectMember("vector<std::vector<Float_t> >", (void*)&sobj->fped, "fped.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fslope", (void*)&sobj->fslope);
      R__insp.InspectMember("vector<std::vector<Float_t> >", (void*)&sobj->fslope, "fslope.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "foffset", (void*)&sobj->foffset);
      R__insp.InspectMember("vector<std::vector<Float_t> >", (void*)&sobj->foffset, "foffset.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fbad", (void*)&sobj->fbad);
      R__insp.InspectMember("vector<std::vector<Int_t> >", (void*)&sobj->fbad, "fbad.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fcrdccal", (void*)&sobj->fcrdccal);
      R__insp.InspectMember("vector<Float_t>", (void*)&sobj->fcrdccal, "fcrdccal.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fts800", &sobj->fts800);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fICoffset", (void*)&sobj->fICoffset);
      R__insp.InspectMember("vector<Float_t>", (void*)&sobj->fICoffset, "fICoffset.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fICslope", (void*)&sobj->fICslope);
      R__insp.InspectMember("vector<Float_t>", (void*)&sobj->fICslope, "fICslope.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fde_slope", &sobj->fde_slope);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fde_offset", &sobj->fde_offset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fcrdc", &sobj->fcrdc);
      R__insp.InspectMember(sobj->fcrdc, "fcrdc.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ftof", &sobj->ftof);
      R__insp.InspectMember(sobj->ftof, "ftof.");
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_S800Calibration(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::S800Calibration : new ::S800Calibration;
   }
   static void *newArray_S800Calibration(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::S800Calibration[nElements] : new ::S800Calibration[nElements];
   }
   // Wrapper around operator delete
   static void delete_S800Calibration(void *p) {
      delete ((::S800Calibration*)p);
   }
   static void deleteArray_S800Calibration(void *p) {
      delete [] ((::S800Calibration*)p);
   }
   static void destruct_S800Calibration(void *p) {
      typedef ::S800Calibration current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::S800Calibration

namespace ROOTDict {
   void vectorlEfloatgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEfloatgR_Dictionary();
   static void *new_vectorlEfloatgR(void *p = 0);
   static void *newArray_vectorlEfloatgR(Long_t size, void *p);
   static void delete_vectorlEfloatgR(void *p);
   static void deleteArray_vectorlEfloatgR(void *p);
   static void destruct_vectorlEfloatgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<float>*)
   {
      vector<float> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<float>", -2, "vector.dll", 0,
                  typeid(vector<float>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<float>) );
      instance.SetNew(&new_vectorlEfloatgR);
      instance.SetNewArray(&newArray_vectorlEfloatgR);
      instance.SetDelete(&delete_vectorlEfloatgR);
      instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
      instance.SetDestructor(&destruct_vectorlEfloatgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<float> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<float>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEfloatgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEfloatgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
   }
   static void *newArray_vectorlEfloatgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEfloatgR(void *p) {
      delete ((vector<float>*)p);
   }
   static void deleteArray_vectorlEfloatgR(void *p) {
      delete [] ((vector<float>*)p);
   }
   static void destruct_vectorlEfloatgR(void *p) {
      typedef vector<float> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<float>

namespace ROOTDict {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<int>

namespace ROOTDict {
   void vectorlEvectorlEfloatgRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEvectorlEfloatgRsPgR_Dictionary();
   static void *new_vectorlEvectorlEfloatgRsPgR(void *p = 0);
   static void *newArray_vectorlEvectorlEfloatgRsPgR(Long_t size, void *p);
   static void delete_vectorlEvectorlEfloatgRsPgR(void *p);
   static void deleteArray_vectorlEvectorlEfloatgRsPgR(void *p);
   static void destruct_vectorlEvectorlEfloatgRsPgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<vector<float> >*)
   {
      vector<vector<float> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<vector<float> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<vector<float> >", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<vector<float> >), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEfloatgRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<vector<float> >) );
      instance.SetNew(&new_vectorlEvectorlEfloatgRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEfloatgRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEfloatgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEfloatgRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEfloatgRsPgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<vector<float> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<vector<float> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvectorlEfloatgRsPgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<vector<float> >*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEvectorlEfloatgRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<float> > : new vector<vector<float> >;
   }
   static void *newArray_vectorlEvectorlEfloatgRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<float> >[nElements] : new vector<vector<float> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvectorlEfloatgRsPgR(void *p) {
      delete ((vector<vector<float> >*)p);
   }
   static void deleteArray_vectorlEvectorlEfloatgRsPgR(void *p) {
      delete [] ((vector<vector<float> >*)p);
   }
   static void destruct_vectorlEvectorlEfloatgRsPgR(void *p) {
      typedef vector<vector<float> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<vector<float> >

namespace ROOTDict {
   void vectorlEvectorlEintgRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEvectorlEintgRsPgR_Dictionary();
   static void *new_vectorlEvectorlEintgRsPgR(void *p = 0);
   static void *newArray_vectorlEvectorlEintgRsPgR(Long_t size, void *p);
   static void delete_vectorlEvectorlEintgRsPgR(void *p);
   static void deleteArray_vectorlEvectorlEintgRsPgR(void *p);
   static void destruct_vectorlEvectorlEintgRsPgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<vector<int> >*)
   {
      vector<vector<int> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<vector<int> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<vector<int> >", -2, "/mnt/misc/sw/x86_64/Debian/8/root/gnu/5.34.32/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<vector<int> >), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEintgRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<vector<int> >) );
      instance.SetNew(&new_vectorlEvectorlEintgRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEintgRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEintgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEintgRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEintgRsPgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<vector<int> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<vector<int> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvectorlEintgRsPgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<vector<int> >*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEvectorlEintgRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<int> > : new vector<vector<int> >;
   }
   static void *newArray_vectorlEvectorlEintgRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<int> >[nElements] : new vector<vector<int> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvectorlEintgRsPgR(void *p) {
      delete ((vector<vector<int> >*)p);
   }
   static void deleteArray_vectorlEvectorlEintgRsPgR(void *p) {
      delete [] ((vector<vector<int> >*)p);
   }
   static void destruct_vectorlEvectorlEintgRsPgR(void *p) {
      typedef vector<vector<int> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<vector<int> >

/********************************************************
* S800CalibrationDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableS800CalibrationDictionary();

extern "C" void G__set_cpp_environmentS800CalibrationDictionary() {
  G__cpp_reset_tagtableS800CalibrationDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevS800CalibrationDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* S800Calibration */
static int G__S800CalibrationDictionary_445_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   S800Calibration* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new S800Calibration[n];
     } else {
       p = new((void*) gvp) S800Calibration[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new S800Calibration;
     } else {
       p = new((void*) gvp) S800Calibration;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   S800Calibration* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new S800Calibration((S800Settings*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) S800Calibration((S800Settings*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->ReadCrdcCalibration((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->ReadCrdcBadPads((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((S800Calibration*) G__getstructoffset())->IsBad((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->S800Calculate((S800*) G__int(libp->para[0]), (S800Calc*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->CrdcCal(*((vector<Short_t>*) G__int(libp->para[0])), *((vector<Short_t>*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Float_t>* pobj;
         vector<Float_t> xobj = ((S800Calibration*) G__getstructoffset())->GetCalibratedCrdcPads(*((vector<Short_t>*) G__int(libp->para[0])), *((vector<Short_t>*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *(vector<Float_t>*) libp->para[3].ref);
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->MakeCalibratedCRDC((CRDC*) G__int(libp->para[0]), *((vector<Short_t>*) G__int(libp->para[1]))
, *((vector<Short_t>*) G__int(libp->para[2])), (Float_t) G__double(libp->para[3])
, (Float_t) G__double(libp->para[4]), (Int_t) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Calibration*) G__getstructoffset())->CalcX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Calibration*) G__getstructoffset())->CalcX2((CRDC*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->SetCrdc(*((vector<Short_t>*) G__int(libp->para[0])), *((vector<Short_t>*) G__int(libp->para[1]))
, (Float_t) G__double(libp->para[2]), (Float_t) G__double(libp->para[3])
, (Int_t) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         CRDC* pobj;
         CRDC xobj = ((S800Calibration*) G__getstructoffset())->GetCrdc();
         pobj = new CRDC(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Calibration*) G__getstructoffset())->TimeOffset((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Calibration*) G__getstructoffset())->TimeOffset((Float_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->SetTof((GTimeOfFlight*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TOF* pobj;
         TOF xobj = ((S800Calibration*) G__getstructoffset())->GetTof();
         pobj = new TOF(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->ReadICCalibration((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Float_t>* pobj;
         vector<Float_t> xobj = ((S800Calibration*) G__getstructoffset())->ICCal(*((vector<int>*) G__int(libp->para[0])), *((vector<float>*) G__int(libp->para[1])));
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Calibration*) G__getstructoffset())->ICSum(*((vector<Float_t>*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((S800Calibration*) G__getstructoffset())->ICDE((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])
, (Float_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((S800Calibration*) G__getstructoffset())->SetTS800((Short_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__S800CalibrationDictionary_445_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<Float_t>* pobj;
         vector<Float_t> xobj = ((S800Calibration*) G__getstructoffset())->GetCRDCCal();
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__S800CalibrationDictionary_445_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   S800Calibration* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new S800Calibration(*(S800Calibration*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef S800Calibration G__TS800Calibration;
static int G__S800CalibrationDictionary_445_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (S800Calibration*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((S800Calibration*) (soff+(sizeof(S800Calibration)*i)))->~G__TS800Calibration();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (S800Calibration*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((S800Calibration*) (soff))->~G__TS800Calibration();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__S800CalibrationDictionary_445_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   S800Calibration* dest = (S800Calibration*) G__getstructoffset();
   *dest = *(S800Calibration*) libp->para[0].ref;
   const S800Calibration& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* S800Calibration */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncS800CalibrationDictionary {
 public:
  G__Sizep2memfuncS800CalibrationDictionary(): p(&G__Sizep2memfuncS800CalibrationDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncS800CalibrationDictionary::*p)();
};

size_t G__get_sizep2memfuncS800CalibrationDictionary()
{
  G__Sizep2memfuncS800CalibrationDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceS800CalibrationDictionary() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableS800CalibrationDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Short_t>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<Float_t> >",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Float_t> >",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float,allocator<float> > >",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<Int_t> >",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Int_t> >",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* S800Calibration */
static void G__setup_memvarS800Calibration(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration));
   { S800Calibration *p; p=(S800Calibration*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Settings),-1,-1,4,"fSett=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<Float_t> >"),-1,4,"fped=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<Float_t> >"),-1,4,"fslope=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<Float_t> >"),-1,4,"foffset=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<Int_t> >"),-1,4,"fbad=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,4,"fcrdccal=",0,(char*)NULL);
   G__memvar_setup((void*)0,115,0,0,-1,G__defined_typename("Short_t"),-1,4,"fts800=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,4,"fICoffset=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,4,"fICslope=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fde_slope=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fde_offset=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_CRDC),-1,-1,4,"fcrdc=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_TOF),-1,-1,4,"ftof=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarS800CalibrationDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncS800Calibration(void) {
   /* S800Calibration */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration));
   G__memfunc_setup("S800Calibration",1363,G__S800CalibrationDictionary_445_0_1, 105, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("S800Calibration",1363,G__S800CalibrationDictionary_445_0_2, 105, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration), -1, 0, 1, 1, 1, 0, "U 'S800Settings' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadCrdcCalibration",1888,G__S800CalibrationDictionary_445_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - filename C - - 10 - pedestalfile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadCrdcBadPads",1415,G__S800CalibrationDictionary_445_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsBad",451,G__S800CalibrationDictionary_445_0_5, 103, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - ch i - - 0 - CrdcId", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("S800Calculate",1145,G__S800CalibrationDictionary_445_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'S800' - 0 - in U 'S800Calc' - 0 - out", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CrdcCal",652,G__S800CalibrationDictionary_445_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - channel u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - data "
"i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCalibratedCrdcPads",2063,G__S800CalibrationDictionary_445_0_8, 117, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 4, 1, 1, 0, 
"u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - channels u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - data "
"i - 'Int_t' 0 - id u 'vector<float,allocator<float> >' 'vector<Float_t>' 1 - PedSubtractedPads", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeCalibratedCRDC",1669,G__S800CalibrationDictionary_445_0_9, 121, -1, -1, 0, 6, 1, 1, 0, 
"U 'CRDC' - 0 - theCRDC u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - channels "
"u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - data f - 'Float_t' 0 - tac "
"f - 'Float_t' 0 - anode i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcX",459,G__S800CalibrationDictionary_445_0_10, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcX2",509,G__S800CalibrationDictionary_445_0_11, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "U 'CRDC' - 0 - theCRDC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCrdc",680,G__S800CalibrationDictionary_445_0_12, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - channel u 'vector<short,allocator<short> >' 'vector<Short_t>' 0 - data "
"f - 'Float_t' 0 - tac f - 'Float_t' 0 - anode "
"i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCrdc",668,G__S800CalibrationDictionary_445_0_13, 117, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_CRDC), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TimeOffset",1014,G__S800CalibrationDictionary_445_0_14, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 1, 0, 
"f - 'Float_t' 0 - time1 f - 'Float_t' 0 - time2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TimeOffset",1014,G__S800CalibrationDictionary_445_0_15, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "f - 'Float_t' 0 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTof",597,G__S800CalibrationDictionary_445_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "U 'GTimeOfFlight' - 0 - tof", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTof",585,G__S800CalibrationDictionary_445_0_17, 117, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_TOF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadICCalibration",1648,G__S800CalibrationDictionary_445_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ICCal",412,G__S800CalibrationDictionary_445_0_19, 117, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 2, 1, 1, 0, 
"u 'vector<int,allocator<int> >' 'vector<int>' 0 - chan u 'vector<float,allocator<float> >' 'vector<float>' 0 - raw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ICSum",449,G__S800CalibrationDictionary_445_0_20, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "u 'vector<float,allocator<float> >' 'vector<Float_t>' 0 - cal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ICDE",277,G__S800CalibrationDictionary_445_0_21, 102, -1, G__defined_typename("Float_t"), 0, 3, 1, 1, 0, 
"f - 'Float_t' 0 - sum f - 'Float_t' 0 - x "
"f - 'Float_t' 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTS800",619,G__S800CalibrationDictionary_445_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "s - 'Short_t' 0 - ts800", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCRDCCal",844,G__S800CalibrationDictionary_445_0_23, 117, G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("S800Calibration", 1363, G__S800CalibrationDictionary_445_0_24, (int) ('i'), G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration), -1, 0, 1, 1, 1, 0, "u 'S800Calibration' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~S800Calibration", 1489, G__S800CalibrationDictionary_445_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__S800CalibrationDictionary_445_0_26, (int) ('u'), G__get_linked_tagnum(&G__S800CalibrationDictionaryLN_S800Calibration), -1, 1, 1, 1, 1, 0, "u 'S800Calibration' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncS800CalibrationDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalS800CalibrationDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcS800CalibrationDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_S800Settings = { "S800Settings" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_S800 = { "S800" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_S800Calibration = { "S800Calibration" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_CRDC = { "CRDC" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_TOF = { "TOF" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_S800Calc = { "S800Calc" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_GTimeOfFlight = { "GTimeOfFlight" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR = { "vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableS800CalibrationDictionary() {
  G__S800CalibrationDictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_S800Settings.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_S800.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_S800Calibration.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_CRDC.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_TOF.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_S800Calc.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_GTimeOfFlight.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableS800CalibrationDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_S800Settings);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_S800);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_S800Calibration),sizeof(S800Calibration),-1,296192,(char*)NULL,G__setup_memvarS800Calibration,G__setup_memfuncS800Calibration);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_CRDC);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_TOF);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_S800Calc);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_GTimeOfFlight);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupS800CalibrationDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupS800CalibrationDictionary()");
  G__set_cpp_environmentS800CalibrationDictionary();
  G__cpp_setup_tagtableS800CalibrationDictionary();

  G__cpp_setup_inheritanceS800CalibrationDictionary();

  G__cpp_setup_typetableS800CalibrationDictionary();

  G__cpp_setup_memvarS800CalibrationDictionary();

  G__cpp_setup_memfuncS800CalibrationDictionary();
  G__cpp_setup_globalS800CalibrationDictionary();
  G__cpp_setup_funcS800CalibrationDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncS800CalibrationDictionary();
  return;
}
class G__cpp_setup_initS800CalibrationDictionary {
  public:
    G__cpp_setup_initS800CalibrationDictionary() { G__add_setup_func("S800CalibrationDictionary",(G__incsetup)(&G__cpp_setupS800CalibrationDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initS800CalibrationDictionary() { G__remove_setup_func("S800CalibrationDictionary"); }
};
G__cpp_setup_initS800CalibrationDictionary G__cpp_setup_initializerS800CalibrationDictionary;

