/********************************************************************
* S800Dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S800Dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS800Dictionary();
extern void G__cpp_setup_inheritanceS800Dictionary();
extern void G__cpp_setup_typetableS800Dictionary();
extern void G__cpp_setup_memvarS800Dictionary();
extern void G__cpp_setup_globalS800Dictionary();
extern void G__cpp_setup_memfuncS800Dictionary();
extern void G__cpp_setup_funcS800Dictionary();
extern void G__set_cpp_environmentS800Dictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "S800.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S800DictionaryLN_TClass;
extern G__linked_taginfo G__S800DictionaryLN_TBuffer;
extern G__linked_taginfo G__S800DictionaryLN_TMemberInspector;
extern G__linked_taginfo G__S800DictionaryLN_TObject;
extern G__linked_taginfo G__S800DictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__S800DictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__S800DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S800DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S800DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800DictionaryLN_GTimeOfFlight;
extern G__linked_taginfo G__S800DictionaryLN_GTrigger;
extern G__linked_taginfo G__S800DictionaryLN_GScintillator;
extern G__linked_taginfo G__S800DictionaryLN_GHodoscope;
extern G__linked_taginfo G__S800DictionaryLN_GIonChamber;
extern G__linked_taginfo G__S800DictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__S800DictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800DictionaryLN_GCrdc;
extern G__linked_taginfo G__S800DictionaryLN_GMultiHitTOF;
extern G__linked_taginfo G__S800DictionaryLN_S800;

/* STUB derived class for protected member access */
