/********************************************************************
* S800CalibrationDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S800CalibrationDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS800CalibrationDictionary();
extern void G__cpp_setup_inheritanceS800CalibrationDictionary();
extern void G__cpp_setup_typetableS800CalibrationDictionary();
extern void G__cpp_setup_memvarS800CalibrationDictionary();
extern void G__cpp_setup_globalS800CalibrationDictionary();
extern void G__cpp_setup_memfuncS800CalibrationDictionary();
extern void G__cpp_setup_funcS800CalibrationDictionary();
extern void G__set_cpp_environmentS800CalibrationDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "S800Calibration.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_S800Settings;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_S800;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_S800Calibration;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_CRDC;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_TOF;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_S800Calc;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_GTimeOfFlight;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__S800CalibrationDictionaryLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
