/********************************************************************
* ScalersDictionary3.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ScalersDictionary3.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableScalersDictionary3();
extern void G__cpp_setup_inheritanceScalersDictionary3();
extern void G__cpp_setup_typetableScalersDictionary3();
extern void G__cpp_setup_memvarScalersDictionary3();
extern void G__cpp_setup_globalScalersDictionary3();
extern void G__cpp_setup_memfuncScalersDictionary3();
extern void G__cpp_setup_funcScalersDictionary3();
extern void G__set_cpp_environmentScalersDictionary3();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Scalers.hh"
#include "LendaScalers.hh"
#include "S800Scalers.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ScalersDictionary3LN_TClass;
extern G__linked_taginfo G__ScalersDictionary3LN_TBuffer;
extern G__linked_taginfo G__ScalersDictionary3LN_TMemberInspector;
extern G__linked_taginfo G__ScalersDictionary3LN_TObject;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScalersDictionary3LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ScalersDictionary3LN__ScalerItemNoHeader;
extern G__linked_taginfo G__ScalersDictionary3LN_Scalers;
extern G__linked_taginfo G__ScalersDictionary3LN_LendaScalers;
extern G__linked_taginfo G__ScalersDictionary3LN_S800Scalers;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEScalerscOallocatorlEScalersgRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEScalerscOallocatorlEScalersgRsPgRcLcLiterator;
extern G__linked_taginfo G__ScalersDictionary3LN_reverse_iteratorlEvectorlEScalerscOallocatorlEScalersgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEScalersmUcOallocatorlEScalersmUgRsPgR;
extern G__linked_taginfo G__ScalersDictionary3LN_vectorlEScalersmUcOallocatorlEScalersmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__ScalersDictionary3LN_reverse_iteratorlEvectorlEScalersmUcOallocatorlEScalersmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<Scalers,allocator<Scalers> > G__vectorlEScalerscOallocatorlEScalersgRsPgR;
typedef vector<Scalers*,allocator<Scalers*> > G__vectorlEScalersmUcOallocatorlEScalersmUgRsPgR;
